// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class TemplateGovernanceMetadata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "default_locale",
                schema: "templatemanagement",
                table: "template",
                type: "character varying(5)",
                maxLength: 5,
                nullable: true);

            migrationBuilder.AddColumn<string[]>(
                name: "link_domains_allowed",
                schema: "templatemanagement",
                table: "template",
                type: "text[]",
                nullable: false,
                defaultValue: new string[0]);

            migrationBuilder.AddColumn<string[]>(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template",
                type: "text[]",
                nullable: false,
                defaultValue: new string[0]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "default_locale",
                schema: "templatemanagement",
                table: "template");

            migrationBuilder.DropColumn(
                name: "link_domains_allowed",
                schema: "templatemanagement",
                table: "template");

            migrationBuilder.DropColumn(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template");
        }
    }
}
