// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class TemplateAuthoring : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "templatemanagement");

            migrationBuilder.CreateTable(
                name: "template",
                schema: "templatemanagement",
                columns: table => new
                {
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    @class = table.Column<string>(name: "class", type: "character varying(20)", maxLength: 20, nullable: false),
                    owner_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    purpose = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    legal_basis = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template", x => x.key);
                });

            migrationBuilder.CreateTable(
                name: "template_version",
                schema: "templatemanagement",
                columns: table => new
                {
                    version = table.Column<int>(type: "integer", nullable: false),
                    template_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    variables_schema = table.Column<string>(type: "jsonb", nullable: true),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    etag = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    editors = table.Column<string[]>(type: "text[]", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template_version", x => new { x.template_key, x.version });
                    table.ForeignKey(
                        name: "FK_template_version_template_template_key",
                        column: x => x.template_key,
                        principalSchema: "templatemanagement",
                        principalTable: "template",
                        principalColumn: "key",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "template_content",
                schema: "templatemanagement",
                columns: table => new
                {
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                    template_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    subject = table.Column<string>(type: "character varying(998)", maxLength: 998, nullable: true),
                    body = table.Column<string>(type: "text", nullable: false),
                    body_text = table.Column<string>(type: "text", nullable: true),
                    body_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template_content", x => new { x.template_key, x.version, x.channel, x.locale });
                    table.ForeignKey(
                        name: "FK_template_content_template_version_template_key_version",
                        columns: x => new { x.template_key, x.version },
                        principalSchema: "templatemanagement",
                        principalTable: "template_version",
                        principalColumns: new[] { "template_key", "version" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_template_application_class",
                schema: "templatemanagement",
                table: "template",
                columns: new[] { "application", "class" });

            migrationBuilder.CreateIndex(
                name: "ux_template_version_single_draft",
                schema: "templatemanagement",
                table: "template_version",
                column: "template_key",
                unique: true,
                filter: "status = 'draft'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "template_content",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "template_version",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "template",
                schema: "templatemanagement");
        }
    }
}
