// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class TemplateLifecycleAudit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "published_at",
                schema: "templatemanagement",
                table: "template_version",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "rolled_back_from",
                schema: "templatemanagement",
                table: "template_version",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "approval",
                schema: "templatemanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_type = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    subject_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    subject_version = table.Column<int>(type: "integer", nullable: false),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    role = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    approver_oid = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    approved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_approval", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "audit_event",
                schema: "templatemanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    seq = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    occurred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    actor_type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    actor_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    action = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    entity_type = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    entity_id = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: false),
                    details = table.Column<string>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_audit_event", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_approval_subject",
                schema: "templatemanagement",
                table: "approval",
                columns: new[] { "subject_type", "subject_id", "subject_version" });

            migrationBuilder.CreateIndex(
                name: "ix_audit_event_entity",
                schema: "templatemanagement",
                table: "audit_event",
                columns: new[] { "entity_type", "entity_id" });

            // Append-only against DML: the row triggers reject UPDATE and
            // DELETE for every role. TRUNCATE and owner-issued DDL (dropping
            // the trigger, altering the table) remain possible until the
            // dedicated database roles arrive in the roles phase.
            migrationBuilder.Sql("""
                CREATE FUNCTION templatemanagement.reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Table %.% is append-only: % is not allowed.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
                END $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON templatemanagement.audit_event
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();

                CREATE TRIGGER trg_approval_append_only
                    BEFORE UPDATE OR DELETE ON templatemanagement.approval
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "approval",
                schema: "templatemanagement");

            migrationBuilder.Sql(
                "DROP FUNCTION IF EXISTS templatemanagement.reject_append_only_mutation() CASCADE;");

            migrationBuilder.DropTable(
                name: "audit_event",
                schema: "templatemanagement");

            migrationBuilder.DropColumn(
                name: "published_at",
                schema: "templatemanagement",
                table: "template_version");

            migrationBuilder.DropColumn(
                name: "rolled_back_from",
                schema: "templatemanagement",
                table: "template_version");
        }
    }
}
