// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Removes the audit trail entities (audit_event, approval) from this
    /// module's model without touching the database: the tables and their data
    /// stay in place, and the dedicated Audit module adopts them through its
    /// own migration history. Ownership moves; nothing is dropped.
    /// </summary>
    public partial class RemoveAuditTrailFromModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty: the model no longer maps the audit trail
            // tables, and the adopting module's migrations take over from here.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty: reverting only restores the mapping in the
            // model snapshot; the tables never left the database.
        }
    }
}
