// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TemplateManagementDbContext))]
    [Migration("20260822234009_LayoutAuthoring")]
    partial class LayoutAuthoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("templatemanagement")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApproverOid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approver_oid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.Property<int>("SubjectVersion")
                        .HasColumnType("integer")
                        .HasColumnName("subject_version");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "SubjectVersion")
                        .HasDatabaseName("ix_approval_subject");

                    b.ToTable("approval", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Seq"));

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_event_entity");

                    b.ToTable("audit_event", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.Layout", b =>
                {
                    b.Property<string>("_key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("DefaultLocale")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("default_locale");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_team");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("_key");

                    b.ToTable("layout", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.LayoutVersion", b =>
                {
                    b.Property<string>("_layoutKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("layout_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("Editors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("editors");

                    b.Property<string>("EntityTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("RolledBackFrom")
                        .HasColumnType("integer")
                        .HasColumnName("rolled_back_from");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("_layoutKey", "Version");

                    b.HasIndex("_layoutKey")
                        .IsUnique()
                        .HasDatabaseName("ux_layout_version_single_draft")
                        .HasFilter("status = 'draft'");

                    b.ToTable("layout_version", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.Template", b =>
                {
                    b.Property<string>("_key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<string>("DefaultLocale")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("default_locale");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_basis");

                    b.PrimitiveCollection<string[]>("LinkDomainsAllowed")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("link_domains_allowed");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_team");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.PrimitiveCollection<string[]>("SensitiveVariables")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sensitive_variables");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("_key");

                    b.HasIndex("Application", "Class")
                        .HasDatabaseName("ix_template_application_class");

                    b.ToTable("template", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateVersion", b =>
                {
                    b.Property<string>("_templateKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("Editors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("editors");

                    b.Property<string>("EntityTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("etag");

                    b.Property<string>("LayoutKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("layout_key");

                    b.Property<int?>("LayoutVersion")
                        .HasColumnType("integer")
                        .HasColumnName("layout_version");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("RolledBackFrom")
                        .HasColumnType("integer")
                        .HasColumnName("rolled_back_from");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VariablesSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_schema");

                    b.HasKey("_templateKey", "Version");

                    b.HasIndex("_templateKey")
                        .IsUnique()
                        .HasDatabaseName("ux_template_version_single_draft")
                        .HasFilter("status = 'draft'");

                    b.ToTable("template_version", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.LayoutVersion", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.TemplateManagement.Domain.Layout", null)
                        .WithMany()
                        .HasForeignKey("_layoutKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("NotificationHub.Api.Modules.TemplateManagement.Domain.LayoutContent", "Contents", b1 =>
                        {
                            b1.Property<string>("LayoutKey")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("layout_key");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.Property<string>("Channel")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("channel");

                            b1.Property<string>("Locale")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("locale");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<string>("BodyHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("body_hash");

                            b1.Property<string>("BodyText")
                                .HasColumnType("text")
                                .HasColumnName("body_text");

                            b1.HasKey("LayoutKey", "Version", "Channel", "Locale");

                            b1.ToTable("layout_content", "templatemanagement");

                            b1.WithOwner()
                                .HasForeignKey("LayoutKey", "Version");
                        });

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateVersion", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.TemplateManagement.Domain.Template", null)
                        .WithMany()
                        .HasForeignKey("_templateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateContent", "Contents", b1 =>
                        {
                            b1.Property<string>("TemplateKey")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("template_key");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.Property<string>("Channel")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("channel");

                            b1.Property<string>("Locale")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("locale");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<string>("BodyHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("body_hash");

                            b1.Property<string>("BodyText")
                                .HasColumnType("text")
                                .HasColumnName("body_text");

                            b1.Property<string>("Subject")
                                .HasMaxLength(998)
                                .HasColumnType("character varying(998)")
                                .HasColumnName("subject");

                            b1.HasKey("TemplateKey", "Version", "Channel", "Locale");

                            b1.ToTable("template_content", "templatemanagement");

                            b1.WithOwner()
                                .HasForeignKey("TemplateKey", "Version");
                        });

                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
