// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Converts audit_event into a table partitioned by month on occurred_at.
    /// PostgreSQL cannot partition an existing table in place, so the
    /// conversion renames the current table, creates the partitioned one with
    /// the same columns and the sequence it already owns, provisions the
    /// monthly partitions covering the existing rows plus two months ahead,
    /// copies the rows, and drops the old table. The primary key gains the
    /// partition column (a PostgreSQL requirement); the append-only trigger is
    /// recreated on the partitioned parent, where it propagates to every
    /// partition, current and future.
    /// </summary>
    public partial class MonthlyAuditEventPartitioning : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.audit_event RENAME TO audit_event_unpartitioned;
                ALTER INDEX templatemanagement."PK_audit_event" RENAME TO "PK_audit_event_unpartitioned";
                ALTER INDEX templatemanagement.ix_audit_event_entity RENAME TO ix_audit_event_unpartitioned_entity;
                ALTER SEQUENCE templatemanagement.audit_event_seq_seq OWNED BY NONE;

                CREATE TABLE templatemanagement.audit_event (
                    id uuid NOT NULL,
                    seq bigint NOT NULL DEFAULT nextval('templatemanagement.audit_event_seq_seq'),
                    occurred_at timestamp with time zone NOT NULL,
                    actor_type character varying(20) NOT NULL,
                    actor_id character varying(200) NOT NULL,
                    application character varying(100),
                    action character varying(100) NOT NULL,
                    entity_type character varying(30) NOT NULL,
                    entity_id character varying(250) NOT NULL,
                    details jsonb NOT NULL,
                    CONSTRAINT "PK_audit_event" PRIMARY KEY (id, occurred_at)
                ) PARTITION BY RANGE (occurred_at);

                ALTER SEQUENCE templatemanagement.audit_event_seq_seq
                    OWNED BY templatemanagement.audit_event.seq;

                CREATE INDEX ix_audit_event_entity
                    ON templatemanagement.audit_event (entity_type, entity_id);

                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON templatemanagement.audit_event
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();
                """);

            // Partitions from the month of the oldest existing event (or the
            // current month, whichever is older) through two months after the
            // newest event or the current month. Names and UTC boundaries match
            // the partition-manager job, which keeps provisioning future months
            // from here on.
            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    current_month date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                    month_cursor date;
                    month_last date;
                    partition_name text;
                BEGIN
                    SELECT LEAST(
                            COALESCE(date_trunc('month', min(occurred_at) AT TIME ZONE 'UTC')::date, current_month),
                            current_month)
                        INTO month_cursor
                        FROM templatemanagement.audit_event_unpartitioned;

                    SELECT (GREATEST(
                            COALESCE(date_trunc('month', max(occurred_at) AT TIME ZONE 'UTC')::date, current_month),
                            current_month) + interval '2 months')::date
                        INTO month_last
                        FROM templatemanagement.audit_event_unpartitioned;

                    WHILE month_cursor <= month_last LOOP
                        partition_name := 'audit_event_' || to_char(month_cursor, 'YYYY_MM');
                        EXECUTE format(
                            'CREATE TABLE IF NOT EXISTS templatemanagement.%I '
                            || 'PARTITION OF templatemanagement.audit_event '
                            || 'FOR VALUES FROM (%L) TO (%L)',
                            partition_name,
                            month_cursor::timestamp AT TIME ZONE 'UTC',
                            (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                        month_cursor := (month_cursor + interval '1 month')::date;
                    END LOOP;

                    INSERT INTO templatemanagement.audit_event
                        (id, seq, occurred_at, actor_type, actor_id, application, action, entity_type, entity_id, details)
                    SELECT id, seq, occurred_at, actor_type, actor_id, application, action, entity_type, entity_id, details
                    FROM templatemanagement.audit_event_unpartitioned;
                END $$;

                DROP TABLE templatemanagement.audit_event_unpartitioned;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.audit_event RENAME TO audit_event_partitioned;
                ALTER INDEX templatemanagement."PK_audit_event" RENAME TO "PK_audit_event_partitioned";
                ALTER INDEX templatemanagement.ix_audit_event_entity RENAME TO ix_audit_event_partitioned_entity;
                ALTER SEQUENCE templatemanagement.audit_event_seq_seq OWNED BY NONE;

                CREATE TABLE templatemanagement.audit_event (
                    id uuid NOT NULL,
                    seq bigint NOT NULL DEFAULT nextval('templatemanagement.audit_event_seq_seq'),
                    occurred_at timestamp with time zone NOT NULL,
                    actor_type character varying(20) NOT NULL,
                    actor_id character varying(200) NOT NULL,
                    application character varying(100),
                    action character varying(100) NOT NULL,
                    entity_type character varying(30) NOT NULL,
                    entity_id character varying(250) NOT NULL,
                    details jsonb NOT NULL,
                    CONSTRAINT "PK_audit_event" PRIMARY KEY (id)
                );

                ALTER SEQUENCE templatemanagement.audit_event_seq_seq
                    OWNED BY templatemanagement.audit_event.seq;

                CREATE INDEX ix_audit_event_entity
                    ON templatemanagement.audit_event (entity_type, entity_id);

                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON templatemanagement.audit_event
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();

                INSERT INTO templatemanagement.audit_event
                    (id, seq, occurred_at, actor_type, actor_id, application, action, entity_type, entity_id, details)
                SELECT id, seq, occurred_at, actor_type, actor_id, application, action, entity_type, entity_id, details
                FROM templatemanagement.audit_event_partitioned;

                DROP TABLE templatemanagement.audit_event_partitioned;
                """);
        }
    }
}
