// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "templatemanagement");

            migrationBuilder.CreateTable(
                name: "class_policy_version",
                schema: "templatemanagement",
                columns: table => new
                {
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    @class = table.Column<string>(name: "class", type: "character varying(20)", maxLength: 20, nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    schema_version = table.Column<int>(type: "integer", nullable: false),
                    definition = table.Column<string>(type: "text", nullable: false),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    published_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    etag = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    editors = table.Column<string[]>(type: "text[]", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_class_policy_version", x => new { x.application, x.@class, x.version });
                });

            migrationBuilder.CreateTable(
                name: "layout",
                schema: "templatemanagement",
                columns: table => new
                {
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    owner_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    default_locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout", x => x.key);
                });

            migrationBuilder.CreateTable(
                name: "lifecycle_note",
                schema: "templatemanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    subject_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    text = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    recorded_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    recorded_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_lifecycle_note", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "template",
                schema: "templatemanagement",
                columns: table => new
                {
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    @class = table.Column<string>(name: "class", type: "character varying(20)", maxLength: 20, nullable: false),
                    owner_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    purpose = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    legal_basis = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    default_locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    link_domains_allowed = table.Column<string[]>(type: "text[]", nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template", x => x.key);
                });

            migrationBuilder.CreateTable(
                name: "layout_version",
                schema: "templatemanagement",
                columns: table => new
                {
                    version = table.Column<int>(type: "integer", nullable: false),
                    layout_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    published_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    rolled_back_from = table.Column<int>(type: "integer", nullable: true),
                    etag = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    editors = table.Column<string[]>(type: "text[]", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout_version", x => new { x.layout_key, x.version });
                    table.ForeignKey(
                        name: "FK_layout_version_layout_layout_key",
                        column: x => x.layout_key,
                        principalSchema: "templatemanagement",
                        principalTable: "layout",
                        principalColumn: "key",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "template_version",
                schema: "templatemanagement",
                columns: table => new
                {
                    version = table.Column<int>(type: "integer", nullable: false),
                    template_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    variables_schema = table.Column<string>(type: "text", nullable: true),
                    layout_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    layout_version = table.Column<int>(type: "integer", nullable: true),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    published_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    rolled_back_from = table.Column<int>(type: "integer", nullable: true),
                    etag = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    editors = table.Column<string[]>(type: "text[]", nullable: false),
                    sensitive_variables = table.Column<string[]>(type: "text[]", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template_version", x => new { x.template_key, x.version });
                    table.ForeignKey(
                        name: "FK_template_version_template_template_key",
                        column: x => x.template_key,
                        principalSchema: "templatemanagement",
                        principalTable: "template",
                        principalColumn: "key",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "layout_content",
                schema: "templatemanagement",
                columns: table => new
                {
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                    layout_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    body = table.Column<string>(type: "text", nullable: false),
                    body_text = table.Column<string>(type: "text", nullable: true),
                    body_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout_content", x => new { x.layout_key, x.version, x.channel, x.locale });
                    table.ForeignKey(
                        name: "FK_layout_content_layout_version_layout_key_version",
                        columns: x => new { x.layout_key, x.version },
                        principalSchema: "templatemanagement",
                        principalTable: "layout_version",
                        principalColumns: new[] { "layout_key", "version" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "template_content",
                schema: "templatemanagement",
                columns: table => new
                {
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                    template_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    subject = table.Column<string>(type: "character varying(998)", maxLength: 998, nullable: true),
                    body = table.Column<string>(type: "text", nullable: false),
                    body_text = table.Column<string>(type: "text", nullable: true),
                    body_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_template_content", x => new { x.template_key, x.version, x.channel, x.locale });
                    table.ForeignKey(
                        name: "FK_template_content_template_version_template_key_version",
                        columns: x => new { x.template_key, x.version },
                        principalSchema: "templatemanagement",
                        principalTable: "template_version",
                        principalColumns: new[] { "template_key", "version" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ux_class_policy_version_single_draft",
                schema: "templatemanagement",
                table: "class_policy_version",
                columns: new[] { "application", "class" },
                unique: true,
                filter: "status = 'draft'");

            migrationBuilder.CreateIndex(
                name: "ux_class_policy_version_single_published",
                schema: "templatemanagement",
                table: "class_policy_version",
                columns: new[] { "application", "class" },
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ux_layout_version_single_draft",
                schema: "templatemanagement",
                table: "layout_version",
                column: "layout_key",
                unique: true,
                filter: "status = 'draft'");

            migrationBuilder.CreateIndex(
                name: "ux_layout_version_single_published",
                schema: "templatemanagement",
                table: "layout_version",
                column: "layout_key",
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ix_lifecycle_note_subject",
                schema: "templatemanagement",
                table: "lifecycle_note",
                columns: new[] { "subject_type", "subject_key" });

            migrationBuilder.CreateIndex(
                name: "ix_template_application_class",
                schema: "templatemanagement",
                table: "template",
                columns: new[] { "application", "class" });

            migrationBuilder.CreateIndex(
                name: "ux_template_version_single_draft",
                schema: "templatemanagement",
                table: "template_version",
                column: "template_key",
                unique: true,
                filter: "status = 'draft'");

            migrationBuilder.CreateIndex(
                name: "ux_template_version_single_published",
                schema: "templatemanagement",
                table: "template_version",
                column: "template_key",
                unique: true,
                filter: "status = 'published'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "class_policy_version",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "layout_content",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "lifecycle_note",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "template_content",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "layout_version",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "template_version",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "layout",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "template",
                schema: "templatemanagement");
        }
    }
}
