// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Moves the declaration of which variables carry sensitive data off the
    /// template identity and onto the version. On the identity the list was
    /// written once, by whoever created the template, and never again: it sat
    /// outside the content hash, so no approval ever covered it, and there was
    /// no act that could correct it. On the version it enters the hash the
    /// publication approval signs, so a second person approves the exact list,
    /// and a wrong one is corrected by the ordinary act: open a draft, edit it,
    /// have somebody else publish it.
    /// <para>
    /// The new column is required with an empty array as its default, and the
    /// old one is dropped without a backfill. Nothing seeds either table, so
    /// there is no row whose declaration this could carry across.
    /// </para>
    /// <para>
    /// The field joins the canonical form unconditionally, so every version
    /// hashes to a different value than before, and a row written by an
    /// earlier deploy keeps a stored hash the code no longer reproduces:
    /// integrity verification would report tampering over content nobody
    /// touched, and publication and rollback refuse on that report. This
    /// migration therefore assumes an empty table, which is what the state of
    /// this system allows today and stops allowing at the first stored version
    /// that has to survive a redeploy.
    /// </para>
    /// </summary>
    public partial class SensitiveVariablesOnVersion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template");

            migrationBuilder.AddColumn<string[]>(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template_version",
                type: "text[]",
                nullable: false,
                defaultValue: Array.Empty<string>());
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // A rollback returns the column to the identity empty: the
            // declarations written per version have no single value to fold
            // back into one row, and picking one would invent a declaration
            // nobody approved. This direction is a data loss, and it is
            // written out anyway so the schema never claims a column the model
            // no longer declares.
            migrationBuilder.DropColumn(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template_version");

            migrationBuilder.AddColumn<string[]>(
                name: "sensitive_variables",
                schema: "templatemanagement",
                table: "template",
                type: "text[]",
                nullable: false,
                defaultValue: Array.Empty<string>());
        }
    }
}
