// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class LayoutAuthoring : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "layout_key",
                schema: "templatemanagement",
                table: "template_version",
                type: "character varying(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "layout_version",
                schema: "templatemanagement",
                table: "template_version",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "layout",
                schema: "templatemanagement",
                columns: table => new
                {
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    owner_team = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    default_locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout", x => x.key);
                });

            migrationBuilder.CreateTable(
                name: "layout_version",
                schema: "templatemanagement",
                columns: table => new
                {
                    version = table.Column<int>(type: "integer", nullable: false),
                    layout_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    published_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    rolled_back_from = table.Column<int>(type: "integer", nullable: true),
                    etag = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    editors = table.Column<string[]>(type: "text[]", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout_version", x => new { x.layout_key, x.version });
                    table.ForeignKey(
                        name: "FK_layout_version_layout_layout_key",
                        column: x => x.layout_key,
                        principalSchema: "templatemanagement",
                        principalTable: "layout",
                        principalColumn: "key",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "layout_content",
                schema: "templatemanagement",
                columns: table => new
                {
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    locale = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                    layout_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    body = table.Column<string>(type: "text", nullable: false),
                    body_text = table.Column<string>(type: "text", nullable: true),
                    body_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_layout_content", x => new { x.layout_key, x.version, x.channel, x.locale });
                    table.ForeignKey(
                        name: "FK_layout_content_layout_version_layout_key_version",
                        columns: x => new { x.layout_key, x.version },
                        principalSchema: "templatemanagement",
                        principalTable: "layout_version",
                        principalColumns: new[] { "layout_key", "version" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ux_layout_version_single_draft",
                schema: "templatemanagement",
                table: "layout_version",
                column: "layout_key",
                unique: true,
                filter: "status = 'draft'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "layout_content",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "layout_version",
                schema: "templatemanagement");

            migrationBuilder.DropTable(
                name: "layout",
                schema: "templatemanagement");

            migrationBuilder.DropColumn(
                name: "layout_key",
                schema: "templatemanagement",
                table: "template_version");

            migrationBuilder.DropColumn(
                name: "layout_version",
                schema: "templatemanagement",
                table: "template_version");
        }
    }
}
