// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Moves the hashed JSON columns from jsonb to plain text so the stored
    /// bytes survive the round trip, adds the xmin concurrency mapping on the
    /// template and layout identities, and creates the partial unique indexes
    /// that back the one-published-version invariant per template, layout and
    /// class policy.
    /// <para>
    /// What the round trip has to preserve is narrower than this comment once
    /// claimed. Key order and whitespace never mattered: the canonical form
    /// sorts object keys and compacts, so a column that reordered or reindented
    /// would still hash the same, and a test pins that. The number literal is
    /// what matters. The canonical form writes a number exactly as it was
    /// submitted, and jsonb re-renders one from numeric, so a schema stored as
    /// jsonb would come back with 1e2 spelled 100 and fail the integrity check
    /// its own approval covered. The decision stands on that one leg.
    /// </para>
    /// </summary>
    public partial class CanonicalTextAndPublicationGuards : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // USING <col>::text preserves the stored representation while
            // changing the column type; without it PostgreSQL has no
            // assignment cast from jsonb to text.
            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.template_version
                    ALTER COLUMN variables_schema TYPE text USING variables_schema::text;
                ALTER TABLE templatemanagement.class_policy_version
                    ALTER COLUMN definition TYPE text USING definition::text;
                """);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "templatemanagement",
                table: "template",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "templatemanagement",
                table: "layout",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.CreateIndex(
                name: "ux_template_version_single_published",
                schema: "templatemanagement",
                table: "template_version",
                column: "template_key",
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ux_layout_version_single_published",
                schema: "templatemanagement",
                table: "layout_version",
                column: "layout_key",
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ux_class_policy_version_single_published",
                schema: "templatemanagement",
                table: "class_policy_version",
                columns: new[] { "application", "class" },
                unique: true,
                filter: "status = 'published'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ux_template_version_single_published",
                schema: "templatemanagement",
                table: "template_version");

            migrationBuilder.DropIndex(
                name: "ux_layout_version_single_published",
                schema: "templatemanagement",
                table: "layout_version");

            migrationBuilder.DropIndex(
                name: "ux_class_policy_version_single_published",
                schema: "templatemanagement",
                table: "class_policy_version");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "templatemanagement",
                table: "template");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "templatemanagement",
                table: "layout");

            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.template_version
                    ALTER COLUMN variables_schema TYPE jsonb USING variables_schema::jsonb;
                ALTER TABLE templatemanagement.class_policy_version
                    ALTER COLUMN definition TYPE jsonb USING definition::jsonb;
                """);
        }
    }
}
