// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Canonizes the purpose of every template identity already stored: lower
    /// case, without surrounding blanks. The aggregate now mints the canonical
    /// form at its only write door, so nothing new can arrive uncanonical, but
    /// rows created before that keep whatever case their author typed, and
    /// every reader of this column compares it with an ordinal equality. A row
    /// left in mixed case reads as a template of some other purpose: its
    /// authentication SMS publishes with a link in it, its render ships that
    /// link, its notification loses the authentication queue, and the go-live
    /// gate, which asks the same question in SQL, does not see it either.
    /// <para>
    /// The statement is idempotent and touches nothing when the column is
    /// already clean, so it is safe to replay and it does not depend on knowing
    /// what production holds. Only this column moves: the audit trail never
    /// recorded the purpose, and the compliance evidence reads the identity row
    /// live, so correcting the row corrects the historical evidence with it.
    /// </para>
    /// </summary>
    public partial class CanonicalTemplatePurpose : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
            => migrationBuilder.Sql("""
                UPDATE templatemanagement.template
                SET purpose = lower(btrim(purpose))
                WHERE purpose <> lower(btrim(purpose));
                """);

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty, and honestly so: lowering case destroys the
            // original spelling, and nothing recorded it, so there is no way
            // back. Reverting this migration leaves the canonical values in
            // place; it does not pretend to restore what they were.
        }
    }
}
