// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Gives the free-text note of a deprecate or a disable a home outside the
    /// audit trail. Until now the operator's prose was serialized into the
    /// details of the trail event, which is append-only by database trigger
    /// and covered by the hash chain of its partition: a national identifier,
    /// an address or a token typed into that box while traffic was being
    /// stopped stayed there for the retention of the trail, with no normal
    /// path to remove it and no way to rewrite the row without breaking the
    /// chain of every event of the month. The trail now records the reason
    /// code and a random reference; the words live in this table, which can be
    /// read, and can be deleted, and whose deletion is itself recorded.
    /// <para>
    /// Nothing is retroactive and nothing can be: the rows written before this
    /// still carry the prose inside the canonical text the hash covers, and
    /// correcting them is exactly what the trail refuses to allow.
    /// </para>
    /// </summary>
    public partial class LifecycleNoteStore : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "lifecycle_note",
                schema: "templatemanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    subject_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    text = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    recorded_by = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    recorded_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_lifecycle_note", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_lifecycle_note_subject",
                schema: "templatemanagement",
                table: "lifecycle_note",
                columns: new[] { "subject_type", "subject_key" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Dropping the table destroys the notes it holds, and the trail
            // keeps only the references that pointed at them: a rollback of
            // this migration is a data loss, not a restoration. It is written
            // out anyway, because a Down that silently does nothing would
            // leave the schema claiming a table the model no longer declares.
            migrationBuilder.DropTable(
                name: "lifecycle_note",
                schema: "templatemanagement");
        }
    }
}
