// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Moves the hashed JSON columns from jsonb to plain text so the stored
    /// bytes survive the round trip (jsonb rewrites number literals, key order
    /// and whitespace, breaking canonical-hash verification), adds the xmin
    /// concurrency mapping on the template and layout identities, and creates
    /// the partial unique indexes that back the one-published-version
    /// invariant per template, layout and class policy.
    /// </summary>
    public partial class CanonicalTextAndPublicationGuards : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // USING <col>::text preserves the stored representation while
            // changing the column type; without it PostgreSQL has no
            // assignment cast from jsonb to text.
            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.template_version
                    ALTER COLUMN variables_schema TYPE text USING variables_schema::text;
                ALTER TABLE templatemanagement.class_policy_version
                    ALTER COLUMN definition TYPE text USING definition::text;
                """);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "templatemanagement",
                table: "template",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "templatemanagement",
                table: "layout",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.CreateIndex(
                name: "ux_template_version_single_published",
                schema: "templatemanagement",
                table: "template_version",
                column: "template_key",
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ux_layout_version_single_published",
                schema: "templatemanagement",
                table: "layout_version",
                column: "layout_key",
                unique: true,
                filter: "status = 'published'");

            migrationBuilder.CreateIndex(
                name: "ux_class_policy_version_single_published",
                schema: "templatemanagement",
                table: "class_policy_version",
                columns: new[] { "application", "class" },
                unique: true,
                filter: "status = 'published'");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ux_template_version_single_published",
                schema: "templatemanagement",
                table: "template_version");

            migrationBuilder.DropIndex(
                name: "ux_layout_version_single_published",
                schema: "templatemanagement",
                table: "layout_version");

            migrationBuilder.DropIndex(
                name: "ux_class_policy_version_single_published",
                schema: "templatemanagement",
                table: "class_policy_version");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "templatemanagement",
                table: "template");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "templatemanagement",
                table: "layout");

            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.template_version
                    ALTER COLUMN variables_schema TYPE jsonb USING variables_schema::jsonb;
                ALTER TABLE templatemanagement.class_policy_version
                    ALTER COLUMN definition TYPE jsonb USING definition::jsonb;
                """);
        }
    }
}
