// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.TemplateManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TemplateManagementDbContext))]
    partial class TemplateManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("templatemanagement")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.Template", b =>
                {
                    b.Property<string>("_key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_basis");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_team");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("_key");

                    b.HasIndex("Application", "Class")
                        .HasDatabaseName("ix_template_application_class");

                    b.ToTable("template", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateVersion", b =>
                {
                    b.Property<string>("_templateKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("Editors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("editors");

                    b.Property<string>("EntityTag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("etag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VariablesSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_schema");

                    b.HasKey("_templateKey", "Version");

                    b.HasIndex("_templateKey")
                        .IsUnique()
                        .HasDatabaseName("ux_template_version_single_draft")
                        .HasFilter("status = 'draft'");

                    b.ToTable("template_version", "templatemanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateVersion", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.TemplateManagement.Domain.Template", null)
                        .WithMany()
                        .HasForeignKey("_templateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("NotificationHub.Api.Modules.TemplateManagement.Domain.TemplateContent", "Contents", b1 =>
                        {
                            b1.Property<string>("TemplateKey")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("template_key");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.Property<string>("Channel")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("channel");

                            b1.Property<string>("Locale")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("locale");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<string>("BodyHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("body_hash");

                            b1.Property<string>("BodyText")
                                .HasColumnType("text")
                                .HasColumnName("body_text");

                            b1.Property<string>("Subject")
                                .HasMaxLength(998)
                                .HasColumnType("character varying(998)")
                                .HasColumnName("subject");

                            b1.HasKey("TemplateKey", "Version", "Channel", "Locale");

                            b1.ToTable("template_content", "templatemanagement");

                            b1.WithOwner()
                                .HasForeignKey("TemplateKey", "Version");
                        });

                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
