// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Infrastructure.Messaging.Migrations
{
    /// <summary>
    /// Adds the transport of each outbox row and rebuilds the pending index
    /// with transport as its leading column. The relay claims one transport
    /// lane at a time, so an unreachable bus never blocks the internal queue
    /// rows of the same priority band; existing rows default to the internal
    /// queues, which is what every producer written so far meant.
    /// </summary>
    public partial class AddOutboxTransport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox");

            migrationBuilder.AddColumn<string>(
                name: "transport",
                schema: "platform",
                table: "outbox",
                type: "character varying(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "sqs");

            migrationBuilder.CreateIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox",
                columns: new[] { "transport", "priority_class", "created_at" },
                filter: "sent_at IS NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox");

            migrationBuilder.DropColumn(
                name: "transport",
                schema: "platform",
                table: "outbox");

            migrationBuilder.CreateIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox",
                columns: new[] { "priority_class", "created_at" },
                filter: "sent_at IS NULL");
        }
    }
}
