// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Infrastructure.Messaging.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "platform");

            migrationBuilder.CreateTable(
                name: "outbox",
                schema: "platform",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    destination = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    transport = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false, defaultValue: "sqs"),
                    event_type = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    message_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    headers = table.Column<string>(type: "jsonb", nullable: false),
                    payload = table.Column<string>(type: "jsonb", nullable: false),
                    priority_class = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    priority_band = table.Column<int>(type: "integer", nullable: false, computedColumnSql: "CASE WHEN destination = 'core-auth' OR (destination LIKE 'dispatch-%' AND destination LIKE '%-auth') THEN 0 WHEN priority_class = 'critical' THEN 1 WHEN priority_class = 'transactional' THEN 2 ELSE 3 END", stored: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    sent_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_outbox", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "processed_messages",
                schema: "platform",
                columns: table => new
                {
                    message_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    consumer = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_processed_messages", x => new { x.message_id, x.consumer });
                });

            migrationBuilder.CreateIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox",
                columns: new[] { "transport", "priority_band", "created_at" },
                filter: "sent_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_processed_messages_processed_at",
                schema: "platform",
                table: "processed_messages",
                column: "processed_at");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "outbox",
                schema: "platform");

            migrationBuilder.DropTable(
                name: "processed_messages",
                schema: "platform");
        }
    }
}
