// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Infrastructure.Messaging.Migrations
{
    /// <summary>
    /// Creates the consumer-side dedupe table: one mark per (message id +
    /// business key, consumer), written inside the transaction of the
    /// message's effect and purged by age after the queue retention window.
    /// </summary>
    public partial class AddProcessedMessages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "processed_messages",
                schema: "platform",
                columns: table => new
                {
                    message_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    consumer = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_processed_messages", x => new { x.message_id, x.consumer });
                });

            migrationBuilder.CreateIndex(
                name: "ix_processed_messages_processed_at",
                schema: "platform",
                table: "processed_messages",
                column: "processed_at");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "processed_messages",
                schema: "platform");
        }
    }
}
