// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Infrastructure.Messaging.Migrations
{
    /// <summary>
    /// Stores the drain band of each outbox row and rebuilds the pending index
    /// around it. The relay used to spell the band as a CASE expression inside
    /// its predicate, which no index answers: the claim of one band scanned the
    /// whole table and sorted the survivors on disk. The band depends only on
    /// the destination and the priority class, both known when the row is
    /// written, so the database computes it once per insert. Adding a stored
    /// generated column rewrites the table, and that rewrite is the backfill:
    /// every row already written gets its band from the same expression.
    ///
    /// Two preconditions belong to whoever applies this. The rewrite walks every
    /// row, delivered ones included, so removing delivered rows first is what
    /// bounds the window; it measured about 3.4 seconds per million rows on a
    /// local bench, and the count in the target environment turns that into an
    /// arithmetic estimate rather than a guess. And the exclusive lock this
    /// takes does not merely wait behind a long transaction: it queues every
    /// statement that arrives after it, ingestion included, so run it under a
    /// lock timeout and reschedule instead of holding the hot path open ended.
    /// </summary>
    public partial class AddOutboxPriorityBand : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox");

            migrationBuilder.AddColumn<int>(
                name: "priority_band",
                schema: "platform",
                table: "outbox",
                type: "integer",
                nullable: false,
                computedColumnSql: "CASE WHEN destination = 'core-auth' OR (destination LIKE 'dispatch-%' AND destination LIKE '%-auth') THEN 0 WHEN priority_class = 'critical' THEN 1 WHEN priority_class = 'transactional' THEN 2 ELSE 3 END",
                stored: true);

            migrationBuilder.CreateIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox",
                columns: new[] { "transport", "priority_band", "created_at" },
                filter: "sent_at IS NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox");

            migrationBuilder.DropColumn(
                name: "priority_band",
                schema: "platform",
                table: "outbox");

            migrationBuilder.CreateIndex(
                name: "ix_outbox_pending",
                schema: "platform",
                table: "outbox",
                columns: new[] { "transport", "priority_class", "created_at" },
                filter: "sent_at IS NULL");
        }
    }
}
