// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Adds what the trail needs to be closed and watched: the checkpoint
    /// table of the periodic chain verification (mutable job state, kept out
    /// of the append-only trail on purpose), the grant role the application
    /// connects under, and the function the closing cycle attaches to a
    /// partition once it must stop receiving rows.
    /// </summary>
    /// <remarks>
    /// The role is created NOLOGIN: it carries the grants, and the login users
    /// of each environment are provisioned by infrastructure and granted into
    /// it. Revoking the insert grant is not enough by itself, because a row
    /// inserted through the partitioned parent is routed to its partition and
    /// the privilege checked is the parent's; the trigger created by the
    /// closing cycle is what actually refuses the write.
    /// </remarks>
    public partial class AddChainVerificationAndClosedPartitionGuards : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "chain_verification_checkpoint",
                schema: "audit",
                columns: table => new
                {
                    partition_name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    last_seq = table.Column<long>(type: "bigint", nullable: false),
                    last_hash = table.Column<byte[]>(type: "bytea", nullable: false),
                    verified_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    fully_verified_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    failure = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    failed_seq = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_chain_verification_checkpoint", x => x.partition_name);
                });

            // Grant role, not a login. Environment users are provisioned by
            // infrastructure and granted into it, so no credential is ever
            // implied by a migration.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'audit_appender') THEN
                        CREATE ROLE audit_appender NOLOGIN;
                    END IF;
                END $$;

                GRANT USAGE ON SCHEMA audit TO audit_appender;
                GRANT INSERT, SELECT ON audit.audit_event TO audit_appender;
                GRANT INSERT, SELECT ON audit.approval TO audit_appender;

                DO $$
                DECLARE
                    child regclass;
                BEGIN
                    EXECUTE format(
                        'GRANT USAGE, SELECT ON SEQUENCE %s TO audit_appender',
                        pg_get_serial_sequence('audit.audit_event', 'seq'));

                    FOR child IN
                        SELECT inhrelid::regclass
                        FROM pg_inherits
                        WHERE inhparent = 'audit.audit_event'::regclass
                    LOOP
                        EXECUTE format('GRANT INSERT, SELECT ON %s TO audit_appender', child);
                    END LOOP;
                END $$;

                ALTER DEFAULT PRIVILEGES IN SCHEMA audit
                    GRANT INSERT, SELECT ON TABLES TO audit_appender;
                """);

            // Attached by the closing cycle to a partition that must stop
            // receiving rows. It is a row trigger because routed inserts reach
            // the partition as rows, never as statements against it.
            migrationBuilder.Sql("""
                CREATE FUNCTION audit.reject_closed_partition_write()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'A partição %.% está fechada: INSERT não é permitido.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME;
                END $$ LANGUAGE plpgsql;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP FUNCTION IF EXISTS audit.reject_closed_partition_write();

                ALTER DEFAULT PRIVILEGES IN SCHEMA audit
                    REVOKE INSERT, SELECT ON TABLES FROM audit_appender;

                DO $$
                DECLARE
                    child regclass;
                BEGIN
                    FOR child IN
                        SELECT inhrelid::regclass
                        FROM pg_inherits
                        WHERE inhparent = 'audit.audit_event'::regclass
                    LOOP
                        EXECUTE format('REVOKE ALL ON %s FROM audit_appender', child);
                    END LOOP;

                    EXECUTE format(
                        'REVOKE ALL ON SEQUENCE %s FROM audit_appender',
                        pg_get_serial_sequence('audit.audit_event', 'seq'));
                END $$;

                REVOKE ALL ON audit.approval FROM audit_appender;
                REVOKE ALL ON audit.audit_event FROM audit_appender;
                REVOKE USAGE ON SCHEMA audit FROM audit_appender;
                DROP ROLE IF EXISTS audit_appender;
                """);

            migrationBuilder.DropTable(
                name: "chain_verification_checkpoint",
                schema: "audit");
        }
    }
}
