// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Indexes the rows written before the chain existed, which is the other
    /// half of the sequence range that the periodic verification and the export
    /// walk. With both halves indexed, each statement carries the predicate of
    /// the partial index that answers it and the ordering the single combined
    /// statement had to pay for disappears from the plan.
    /// </summary>
    /// <remarks>
    /// It is free on the write path. Pre-chain rows are a closed set that never
    /// grows, so an inserted row never matches <c>hash IS NULL</c> and never
    /// enters this index. What it buys is a partition answering "there are no
    /// pre-chain rows here" in one lookup instead of scanning the month to
    /// prove an absence. Declared on the partitioned parent, like every other
    /// index of this table, so PostgreSQL propagates it to existing partitions
    /// and to the ones the provisioner creates later; the provisioner needs no
    /// change for that. Building it locks the parent and builds on each
    /// attached partition, and a concurrent build exists neither for a
    /// partitioned table nor inside a migration transaction, so on a populated
    /// database this belongs to the same maintenance window as the tail index.
    /// </remarks>
    public partial class AddPreChainSequenceIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "ix_audit_event_prechain_seq",
                schema: "audit",
                table: "audit_event",
                column: "seq",
                filter: "hash IS NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_audit_event_prechain_seq",
                schema: "audit",
                table: "audit_event");
        }
    }
}
