// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Indexes the tail of the hash chain, which every append reads inside the
    /// partition advisory lock. Until now nothing answered that read: with
    /// partition pruning the plan was a sequential scan of the whole monthly
    /// partition plus a top-N sort, taken with the lock already held, so the
    /// serialization window grew with the size of the month.
    /// </summary>
    /// <remarks>
    /// Partial and descending on the sequence alone. Pruning already satisfies
    /// the time predicate inside a partition, so a composite led by the
    /// partition column is a useless prefix, and the remaining predicate is a
    /// range rather than an equality, which leaves the composite no ordering by
    /// sequence to offer; the planner confirms it by ignoring such an index.
    /// The filter must appear literally in the reading statement for the
    /// planner to match a partial index. It is created on the partitioned
    /// parent, so PostgreSQL builds it on every partition that exists and on
    /// every partition created afterwards, which is what keeps a future month
    /// from silently reintroducing the scan.
    /// <para>
    /// Creating it on the parent takes a lock over the parent and builds the
    /// index on each attached partition, so on a database that already holds
    /// years of the trail this migration is a maintenance window, not a
    /// transparent deploy. The concurrent build that would avoid it is not
    /// available on a partitioned table and not available inside a migration
    /// transaction; the path there is to build per partition outside the
    /// migration and attach.
    /// </para>
    /// </remarks>
    public partial class AddChainTailIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "ix_audit_event_chain_tail",
                schema: "audit",
                table: "audit_event",
                column: "seq",
                descending: [],
                filter: "hash IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_audit_event_chain_tail",
                schema: "audit",
                table: "audit_event");
        }
    }
}
