// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "audit");

            migrationBuilder.CreateTable(
                name: "approval",
                schema: "audit",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_type = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    subject_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    subject_version = table.Column<int>(type: "integer", nullable: false),
                    content_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    role = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    approver_oid = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    approved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_approval", x => x.id);
                });

            // Born partitioned by month on the occurrence instant. The
            // relational model cannot express partitioning, so the trail
            // parent is written as SQL; the primary key is composite because a
            // unique index on a partitioned table must carry the partition
            // column. The three chain columns are nullable together: a row
            // written before the chain existed stays unchained, and the check
            // constraint pins each row to all-or-none of them.
            migrationBuilder.Sql("""
                CREATE TABLE audit.audit_event (
                    id uuid NOT NULL,
                    occurred_at timestamp with time zone NOT NULL,
                    seq bigserial NOT NULL,
                    actor_type character varying(20) NOT NULL,
                    actor_id character varying(200) NOT NULL,
                    application character varying(100),
                    action character varying(100) NOT NULL,
                    entity_type character varying(30) NOT NULL,
                    entity_id character varying(250) NOT NULL,
                    details jsonb NOT NULL,
                    canonical text,
                    prev_hash bytea,
                    hash bytea,
                    CONSTRAINT "PK_audit_event" PRIMARY KEY (id, occurred_at),
                    CONSTRAINT ck_audit_event_chain_complete CHECK (
                        (canonical IS NULL AND prev_hash IS NULL AND hash IS NULL)
                        OR (canonical IS NOT NULL AND prev_hash IS NOT NULL AND hash IS NOT NULL))
                ) PARTITION BY RANGE (occurred_at);
                """);

            migrationBuilder.CreateTable(
                name: "chain_verification_checkpoint",
                schema: "audit",
                columns: table => new
                {
                    partition_name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    last_seq = table.Column<long>(type: "bigint", nullable: false),
                    last_hash = table.Column<byte[]>(type: "bytea", nullable: false),
                    verified_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    fully_verified_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    failure = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    failed_seq = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_chain_verification_checkpoint", x => x.partition_name);
                });

            migrationBuilder.CreateIndex(
                name: "ix_approval_subject",
                schema: "audit",
                table: "approval",
                columns: new[] { "subject_type", "subject_id", "subject_version" });

            migrationBuilder.CreateIndex(
                name: "ix_audit_event_chain_tail",
                schema: "audit",
                table: "audit_event",
                column: "seq",
                descending: new bool[0],
                filter: "hash IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_audit_event_entity",
                schema: "audit",
                table: "audit_event",
                columns: new[] { "entity_type", "entity_id" });

            migrationBuilder.CreateIndex(
                name: "ix_audit_event_prechain_seq",
                schema: "audit",
                table: "audit_event",
                column: "seq",
                filter: "hash IS NULL");

            // The current month plus two, with the same names and the same UTC
            // boundaries the partition-manager job uses when it keeps
            // provisioning months ahead.
            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    month_cursor date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                    month_last date;
                    partition_name text;
                BEGIN
                    month_last := (month_cursor + interval '2 months')::date;
                    WHILE month_cursor <= month_last LOOP
                        partition_name := 'audit_event_' || to_char(month_cursor, 'YYYY_MM');
                        EXECUTE format(
                            'CREATE TABLE IF NOT EXISTS audit.%I '
                            || 'PARTITION OF audit.audit_event '
                            || 'FOR VALUES FROM (%L) TO (%L)',
                            partition_name,
                            month_cursor::timestamp AT TIME ZONE 'UTC',
                            (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                        month_cursor := (month_cursor + interval '1 month')::date;
                    END LOOP;
                END $$;
                """);

            // The trail is append-only in the database, not only in the code
            // that writes it. The trigger on the partitioned parent propagates
            // to every partition, present and future.
            migrationBuilder.Sql("""
                CREATE FUNCTION audit.reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Table %.% is append-only: % is not allowed.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
                END $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON audit.audit_event
                    FOR EACH ROW EXECUTE FUNCTION audit.reject_append_only_mutation();

                CREATE TRIGGER trg_approval_append_only
                    BEFORE UPDATE OR DELETE ON audit.approval
                    FOR EACH ROW EXECUTE FUNCTION audit.reject_append_only_mutation();
                """);

            // Grant role, not a login. Environment users are provisioned by
            // infrastructure and granted into it, so no credential is ever
            // implied by a migration.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'audit_appender') THEN
                        CREATE ROLE audit_appender NOLOGIN;
                    END IF;
                END $$;

                GRANT USAGE ON SCHEMA audit TO audit_appender;
                GRANT INSERT, SELECT ON audit.audit_event TO audit_appender;
                GRANT INSERT, SELECT ON audit.approval TO audit_appender;

                DO $$
                DECLARE
                    child regclass;
                BEGIN
                    EXECUTE format(
                        'GRANT USAGE, SELECT ON SEQUENCE %s TO audit_appender',
                        pg_get_serial_sequence('audit.audit_event', 'seq'));

                    FOR child IN
                        SELECT inhrelid::regclass
                        FROM pg_inherits
                        WHERE inhparent = 'audit.audit_event'::regclass
                    LOOP
                        EXECUTE format('GRANT INSERT, SELECT ON %s TO audit_appender', child);
                    END LOOP;
                END $$;

                ALTER DEFAULT PRIVILEGES IN SCHEMA audit
                    GRANT INSERT, SELECT ON TABLES TO audit_appender;
                """);

            // Attached by the closing cycle to a partition that must stop
            // receiving rows. It is a row trigger because routed inserts reach
            // the partition as rows, never as statements against it.
            migrationBuilder.Sql("""
                CREATE FUNCTION audit.reject_closed_partition_write()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'A partição %.% está fechada: INSERT não é permitido.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME;
                END $$ LANGUAGE plpgsql;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // The role survives on purpose: it may hold grants in schemas this
            // context does not own, and dropping a shared principal from a
            // module rollback would take those with it. Its default privileges
            // in this schema go, because they were declared here.
            migrationBuilder.Sql("""
                ALTER DEFAULT PRIVILEGES IN SCHEMA audit
                    REVOKE INSERT, SELECT ON TABLES FROM audit_appender;
                """);

            migrationBuilder.DropTable(
                name: "approval",
                schema: "audit");

            migrationBuilder.DropTable(
                name: "audit_event",
                schema: "audit");

            migrationBuilder.DropTable(
                name: "chain_verification_checkpoint",
                schema: "audit");

            migrationBuilder.Sql("""
                DROP FUNCTION IF EXISTS audit.reject_closed_partition_write();
                DROP FUNCTION IF EXISTS audit.reject_append_only_mutation();
                """);
        }
    }
}
