// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Adopts the audit trail tables created under the templatemanagement
    /// schema by that module's migration history: audit_event (partitioned by
    /// month, with its sequence, indexes and partitions) and approval move to
    /// the audit schema with their data intact, the append-only triggers are
    /// re-pointed to a function this module owns, and the hash-chain columns
    /// (canonical, prev_hash, hash) join the partitioned parent. Rows written
    /// before the chain keep the three columns absent: nothing is fabricated
    /// retroactively, and the first chained event of each partition links to
    /// that partition's deterministic anchor instead of a forged predecessor.
    /// </summary>
    public partial class AdoptAuditTrail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The trail tables come from the origin module's history; without
            // them there is nothing to adopt and continuing would fork the
            // schema, so the adoption fails loudly with the fix spelled out.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF to_regclass('templatemanagement.audit_event') IS NULL
                        OR to_regclass('templatemanagement.approval') IS NULL THEN
                        RAISE EXCEPTION
                            'As tabelas templatemanagement.audit_event/approval não existem. '
                            'Aplique primeiro as migrações do módulo TemplateManagement e repita esta migração.';
                    END IF;
                END $$;
                """);

            migrationBuilder.EnsureSchema(name: "audit");

            // SET SCHEMA carries the primary keys, the entity indexes and the
            // sequence owned by audit_event.seq; the partitions stay attached
            // across schemas and are moved one by one right after the parent.
            migrationBuilder.Sql("""
                ALTER TABLE templatemanagement.approval SET SCHEMA audit;
                ALTER TABLE templatemanagement.audit_event SET SCHEMA audit;

                DO $$
                DECLARE
                    child regclass;
                BEGIN
                    FOR child IN
                        SELECT inhrelid::regclass
                        FROM pg_inherits
                        WHERE inhparent = 'audit.audit_event'::regclass
                    LOOP
                        EXECUTE format('ALTER TABLE %s SET SCHEMA audit', child);
                    END LOOP;
                END $$;
                """);

            // The adopted tables must not depend on a function owned by the
            // origin module's schema: this module ships its own copy and the
            // recreated triggers on the partitioned parent propagate to every
            // partition, current and future.
            migrationBuilder.Sql("""
                CREATE FUNCTION audit.reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Table %.% is append-only: % is not allowed.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
                END $$ LANGUAGE plpgsql;

                DROP TRIGGER trg_audit_event_append_only ON audit.audit_event;
                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON audit.audit_event
                    FOR EACH ROW EXECUTE FUNCTION audit.reject_append_only_mutation();

                DROP TRIGGER trg_approval_append_only ON audit.approval;
                CREATE TRIGGER trg_approval_append_only
                    BEFORE UPDATE OR DELETE ON audit.approval
                    FOR EACH ROW EXECUTE FUNCTION audit.reject_append_only_mutation();
                """);

            // Chain columns on the partitioned parent propagate to every
            // partition. Nullable on purpose: pre-chain rows stay unchained,
            // and the constraint pins each row to all-or-none of the three.
            migrationBuilder.Sql("""
                ALTER TABLE audit.audit_event
                    ADD COLUMN canonical text,
                    ADD COLUMN prev_hash bytea,
                    ADD COLUMN hash bytea,
                    ADD CONSTRAINT ck_audit_event_chain_complete CHECK (
                        (canonical IS NULL AND prev_hash IS NULL AND hash IS NULL)
                        OR (canonical IS NOT NULL AND prev_hash IS NOT NULL AND hash IS NOT NULL));
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE audit.audit_event
                    DROP CONSTRAINT ck_audit_event_chain_complete,
                    DROP COLUMN canonical,
                    DROP COLUMN prev_hash,
                    DROP COLUMN hash;

                DROP TRIGGER trg_audit_event_append_only ON audit.audit_event;
                CREATE TRIGGER trg_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON audit.audit_event
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();

                DROP TRIGGER trg_approval_append_only ON audit.approval;
                CREATE TRIGGER trg_approval_append_only
                    BEFORE UPDATE OR DELETE ON audit.approval
                    FOR EACH ROW EXECUTE FUNCTION templatemanagement.reject_append_only_mutation();

                DROP FUNCTION audit.reject_append_only_mutation();

                DO $$
                DECLARE
                    child regclass;
                BEGIN
                    FOR child IN
                        SELECT inhrelid::regclass
                        FROM pg_inherits
                        WHERE inhparent = 'audit.audit_event'::regclass
                    LOOP
                        EXECUTE format('ALTER TABLE %s SET SCHEMA templatemanagement', child);
                    END LOOP;
                END $$;

                ALTER TABLE audit.audit_event SET SCHEMA templatemanagement;
                ALTER TABLE audit.approval SET SCHEMA templatemanagement;
                """);
        }
    }
}
