// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.Audit.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.Audit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.Audit.Domain.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApproverOid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approver_oid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.Property<int>("SubjectVersion")
                        .HasColumnType("integer")
                        .HasColumnName("subject_version");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "SubjectVersion")
                        .HasDatabaseName("ix_approval_subject");

                    b.ToTable("approval", "audit");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Audit.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("Canonical")
                        .HasColumnType("text")
                        .HasColumnName("canonical");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<byte[]>("PrevHash")
                        .HasColumnType("bytea")
                        .HasColumnName("prev_hash");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Seq"));

                    b.HasKey("Id", "OccurredAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_event_entity");

                    b.ToTable("audit_event", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_chain_complete", "(canonical IS NULL AND prev_hash IS NULL AND hash IS NULL) OR (canonical IS NOT NULL AND prev_hash IS NOT NULL AND hash IS NOT NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
