// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260823085332_CreateNotificationIngestion")]
    partial class CreateNotificationIngestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.IdempotencyRegistration", b =>
                {
                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.HasKey("Application", "IdempotencyKey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_key_created_at");

                    b.ToTable("idempotency_key", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset?>("ReleaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<byte[]>("VariablesEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("variables_enc");

                    b.Property<string>("VariablesMaskedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_masked");

                    b.HasKey("Id", "CreatedAt");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_notification_correlation");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notification_recipient");

                    b.ToTable("notification", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
