// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Freezes the delivery plan each notification was admitted under. Until
    /// now the fallback re-derived the next step from whatever class policy was
    /// published at the moment the deadline elapsed, which broke two things at
    /// once.
    /// <para>
    /// Republication is the documented way a plan is activated and rolled back,
    /// so re-deriving made both operations change the behaviour of
    /// notifications already accepted: a rollback presented as safe silently
    /// altered messages in flight.
    /// </para>
    /// <para>
    /// And the published plan is not the plan the notification was accepted
    /// under. The Policy stage filters it by the channels the class allows, the
    /// channels the published version ships content for, the channels the
    /// recipient can be reached on, consent and suppression; that filtering
    /// lived only in memory, so the fallback could advance to a channel the
    /// admission had already refused, and write an attempt against a
    /// destination the same notification's trail records as suppressed.
    /// </para>
    /// <para>
    /// What the column deliberately does not freeze is eligibility. Consent and
    /// suppression are re-read when the next step is chosen, because a
    /// destination that died between the admission and the deadline must not be
    /// addressed: the stored plan says which channels are in play and in what
    /// order, and the ledger says whether the one that comes next may still be
    /// used.
    /// </para>
    /// <para>
    /// Rows written before this migration read null, and the fallback falls
    /// back to the published plan for those: refusing to advance over a column
    /// the row could not have had would lose an authentication code to a
    /// migration. Adding a nullable column with no default is a catalog-only
    /// operation on PostgreSQL and rewrites neither the parent nor its
    /// partitions; the lock it takes on the parent is still exclusive and still
    /// blocks the ingestion behind it, which is why the lock timeout applies
    /// here as it does to every migration of this class.
    /// </para>
    /// </summary>
    public partial class AddNotificationAdmittedPlan : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "admitted_plan",
                schema: "notifications",
                table: "notification",
                type: "jsonb",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "admitted_plan",
                schema: "notifications",
                table: "notification");
        }
    }
}
