// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations;

/// <summary>
/// Adds the state the scheduler's scans read, and narrows the two indexes that
/// answer them so each one holds only the rows its scan can still act on.
/// <para>
/// <c>status_changed_at</c> answers how long an attempt has been where it is,
/// which is the question the scan of inconclusive verdicts asks and the only
/// question the creation instant cannot answer. Every row written before this
/// migration reads null and therefore never matches an age predicate. That is
/// accepted rather than backfilled: an invented age would make the scan act on
/// attempts whose real age nobody knows, and the reconciliation job of a later
/// slice is the declared owner of the attempts that were already parked when
/// this column arrived.
/// </para>
/// <para>
/// <c>fallback_requested_at</c> is what keeps the deadline scan from writing
/// one trigger per round for the same attempt. The plan claim cannot serve
/// that purpose, because it belongs to the handler and a scan that stamped it
/// would make the handler drop the very trigger the scan asked for. It is
/// carried in the partial index predicate, so an attempt whose trigger is in
/// flight leaves the index the scan reads and comes back only if the request
/// ages out unanswered.
/// </para>
/// <para>
/// The release index moves from the presence of a release instant to the
/// deferred state. A released notification keeps its instant as evidence of
/// why it waited, so the old filter held every notification that was ever
/// deferred and grew without bound while the scan only ever wanted the ones
/// still waiting.
/// </para>
/// <para>
/// Two nullable columns are catalog-only operations and rewrite no table. The
/// index rebuilds are what take a lock that blocks writes, and a lock that
/// waits behind a long transaction does not merely wait: it queues everything
/// that arrives after it. Hence the lock timeout, which is this repository's
/// standard for a migration of this class.
/// </para>
/// </summary>
public partial class AddSchedulerScanState : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropIndex(
            name: "ix_notification_release",
            schema: "notifications",
            table: "notification");

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "status_changed_at",
            schema: "notifications",
            table: "notification_attempt",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "fallback_requested_at",
            schema: "notifications",
            table: "notification_attempt",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt",
            columns: ["status", "fallback_deadline"],
            filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL "
                + "AND fallback_requested_at IS NULL");

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_unknown_due",
            schema: "notifications",
            table: "notification_attempt",
            column: "status_changed_at",
            filter: "status = 'unknown' AND fallback_deadline IS NOT NULL "
                + "AND plan_advanced_at IS NULL AND fallback_requested_at IS NULL");

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_fallback_inflight",
            schema: "notifications",
            table: "notification_attempt",
            column: "fallback_requested_at",
            filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL "
                + "AND fallback_requested_at IS NOT NULL");

        migrationBuilder.CreateIndex(
            name: "ix_notification_release_due",
            schema: "notifications",
            table: "notification",
            column: "release_at",
            filter: "status = 'deferred'");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_unknown_due",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_fallback_inflight",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropIndex(
            name: "ix_notification_release_due",
            schema: "notifications",
            table: "notification");

        migrationBuilder.DropColumn(
            name: "status_changed_at",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropColumn(
            name: "fallback_requested_at",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt",
            columns: ["status", "fallback_deadline"],
            filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL");

        migrationBuilder.CreateIndex(
            name: "ix_notification_release",
            schema: "notifications",
            table: "notification",
            column: "release_at",
            filter: "release_at IS NOT NULL");
    }
}
