// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations;

/// <summary>
/// Creates the delivery-evidence state of the Notifications context: the
/// delivery_event table born as a parent partitioned by month on received_at
/// (the instant this hub took the callback, never the instant the provider
/// claims, because a provider may date an event backwards and the row would
/// fall outside every provisioned partition), with the initial monthly
/// partitions provisioned here using the same names and UTC boundaries as the
/// partition-manager job; the unpartitioned deduplication ledger, whose
/// unique key must span the provider and its event identity alone; and the
/// partial index that joins feedback carrying no correlation back to the
/// attempt that produced the provider message.
/// </summary>
public partial class AddDeliveryTracking : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Standing rule for any migration of this class: the index over the
        // attempt table takes a lock that blocks writes, and a lock that waits
        // behind a long transaction does not merely wait, it queues everything
        // arriving after it. Failing fast and rescheduling costs less than
        // stalling ingestion for an unbounded time.
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.Sql("""
            CREATE TABLE notifications.delivery_event (
                id uuid NOT NULL,
                received_at timestamp with time zone NOT NULL,
                attempt_id uuid,
                notification_id uuid,
                provider_key character varying(50) NOT NULL,
                provider_event_id character varying(200) NOT NULL,
                provider_message_id character varying(200),
                kind character varying(20) NOT NULL,
                occurred_at timestamp with time zone NOT NULL,
                error_code character varying(100),
                payload_enc bytea NOT NULL,
                applied_at timestamp with time zone,
                CONSTRAINT "PK_delivery_event" PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """);

        migrationBuilder.Sql("""
            DO $$
            DECLARE
                month_start date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                month_cursor date;
                month_last date;
                partition_name text;
            BEGIN
                month_last := (month_start + interval '2 months')::date;
                month_cursor := month_start;
                WHILE month_cursor <= month_last LOOP
                    partition_name := 'delivery_event_' || to_char(month_cursor, 'YYYY_MM');
                    EXECUTE format(
                        'CREATE TABLE IF NOT EXISTS notifications.%I '
                        || 'PARTITION OF notifications.delivery_event '
                        || 'FOR VALUES FROM (%L) TO (%L)',
                        partition_name,
                        month_cursor::timestamp AT TIME ZONE 'UTC',
                        (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                    month_cursor := (month_cursor + interval '1 month')::date;
                END LOOP;
            END $$;
            """);

        migrationBuilder.CreateTable(
            name: "provider_event_dedupe",
            schema: "notifications",
            columns: table => new
            {
                provider = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                provider_event_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_provider_event_dedupe", x => new { x.provider, x.provider_event_id });
            });

        migrationBuilder.CreateIndex(
            name: "ix_delivery_event_attempt",
            schema: "notifications",
            table: "delivery_event",
            column: "attempt_id",
            filter: "attempt_id IS NOT NULL");

        migrationBuilder.CreateIndex(
            name: "ix_delivery_event_notification",
            schema: "notifications",
            table: "delivery_event",
            column: "notification_id",
            filter: "notification_id IS NOT NULL");

        migrationBuilder.CreateIndex(
            name: "ix_provider_event_dedupe_processed",
            schema: "notifications",
            table: "provider_event_dedupe",
            column: "processed_at");

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_provider_message",
            schema: "notifications",
            table: "notification_attempt",
            column: "provider_message_id",
            filter: "provider_message_id IS NOT NULL");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.Sql("DROP TABLE notifications.delivery_event");

        migrationBuilder.DropTable(
            name: "provider_event_dedupe",
            schema: "notifications");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_provider_message",
            schema: "notifications",
            table: "notification_attempt");
    }
}
