// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Creates the producer registry: which bus principal may request which
    /// class for which application. Structure only, on purpose. The grants are
    /// declarative data of the infrastructure repository, materialized here by
    /// a deploy job, so every grant carries the review trail of the change that
    /// created it; seeding them from application configuration would be a
    /// second source of authorization outside that trail.
    /// </summary>
    public partial class AddProducerRegistry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "producer_registry",
                schema: "notifications",
                columns: table => new
                {
                    principal = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    @class = table.Column<string>(name: "class", type: "character varying(20)", maxLength: 20, nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_producer_registry", x => new { x.principal, x.application, x.@class });
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "producer_registry",
                schema: "notifications");
        }
    }
}
