// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Adds the nullable device_token_id column to notification_attempt: the
    /// logical reference the push fan-out stamps per sibling, with no physical
    /// foreign key across module schemas, mirroring contact_point_id.
    /// </summary>
    public partial class AddAttemptDeviceToken : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "device_token_id",
                schema: "notifications",
                table: "notification_attempt",
                type: "uuid",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "device_token_id",
                schema: "notifications",
                table: "notification_attempt");
        }
    }
}
