// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <summary>
        /// The reconciliation index, written by hand because the expression it
        /// is built on is not something the model can carry. It is the same
        /// coalesce the candidate statement spells, so the two are read
        /// together or not at all.
        /// </summary>
        internal const string ReconciliationDueIndexSql = """
            CREATE INDEX ix_notification_attempt_reconciliation_due
                ON notifications.notification_attempt (COALESCE(status_changed_at, created_at))
             WHERE status IN ('sent', 'unknown')
               AND provider_key IS NOT NULL
            """;

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "notifications");

            // Born partitioned by month. A unique index on a partitioned table
            // must contain the partition column, which is why every primary
            // key below is composite. The relational model has no way to say
            // "partition by", so the five parents are written as SQL while the
            // rest of this file stays as the tooling emitted it.
            migrationBuilder.Sql("""
                CREATE TABLE notifications.delivery_event (
                    id uuid NOT NULL,
                    received_at timestamp with time zone NOT NULL,
                    attempt_id uuid,
                    notification_id uuid,
                    provider_key character varying(50) NOT NULL,
                    provider_event_id character varying(200) NOT NULL,
                    provider_message_id character varying(200),
                    kind character varying(20) NOT NULL,
                    occurred_at timestamp with time zone NOT NULL,
                    error_code character varying(100),
                    suppression_signal character varying(30) NOT NULL,
                    payload_id uuid NOT NULL,
                    applied_at timestamp with time zone,
                    suppression_reported_at timestamp with time zone,
                    CONSTRAINT "PK_delivery_event" PRIMARY KEY (id, received_at)
                ) PARTITION BY RANGE (received_at);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE notifications.delivery_payload (
                    id uuid NOT NULL,
                    received_at timestamp with time zone NOT NULL,
                    provider_key character varying(50) NOT NULL,
                    source character varying(20) NOT NULL,
                    payload_enc bytea NOT NULL,
                    CONSTRAINT "PK_delivery_payload" PRIMARY KEY (id, received_at)
                ) PARTITION BY RANGE (received_at);
                """);

            migrationBuilder.CreateTable(
                name: "idempotency_key",
                schema: "notifications",
                columns: table => new
                {
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    idempotency_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    payload_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    notification_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_idempotency_key", x => new { x.application, x.idempotency_key });
                });

            migrationBuilder.CreateTable(
                name: "kill_switch",
                schema: "notifications",
                columns: table => new
                {
                    scope = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    state = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    version = table.Column<long>(type: "bigint", nullable: false),
                    actor = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    second_actor = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_kill_switch", x => new { x.scope, x.key });
                    table.CheckConstraint("ck_kill_switch_scope", "scope IN ('producer', 'application', 'channel')");
                    table.CheckConstraint("ck_kill_switch_state", "state IN ('active', 'inactive')");
                    table.CheckConstraint("ck_kill_switch_version", "version > 0");
                });

            migrationBuilder.CreateTable(
                name: "kill_switch_hold",
                schema: "notifications",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    work_kind = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    work_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    scope = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    destination = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    payload = table.Column<string>(type: "jsonb", nullable: false),
                    expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    released_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_kill_switch_hold", x => x.id);
                    table.CheckConstraint("ck_kill_switch_hold_scope", "scope IN ('producer', 'application', 'channel')");
                    table.CheckConstraint("ck_kill_switch_hold_version", "version > 0");
                    table.CheckConstraint("ck_kill_switch_hold_work_kind", "work_kind IN ('core', 'fallback', 'dispatch')");
                });

            migrationBuilder.Sql("""
                CREATE TABLE notifications.notification (
                    id uuid NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    application character varying(100) NOT NULL,
                    idempotency_key character varying(200) NOT NULL,
                    recipient_id character varying(100) NOT NULL,
                    class character varying(20) NOT NULL,
                    template_key character varying(200) NOT NULL,
                    auth_flow boolean NOT NULL DEFAULT false,
                    template_version integer NOT NULL,
                    policy_version integer,
                    admitted_plan jsonb,
                    accepted_attachments jsonb,
                    variables_masked jsonb NOT NULL,
                    variables_enc bytea,
                    correlation_id character varying(200),
                    requested_by character varying(200) NOT NULL,
                    status character varying(30) NOT NULL,
                    release_at timestamp with time zone,
                    expires_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_notification" PRIMARY KEY (id, created_at)
                ) PARTITION BY RANGE (created_at);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE notifications.notification_attempt (
                    id uuid NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    notification_id uuid NOT NULL,
                    sequence integer NOT NULL,
                    channel character varying(20) NOT NULL,
                    provider_key character varying(50),
                    contact_point_id uuid,
                    device_token_id uuid,
                    provider_message_id character varying(200),
                    rendered_content_enc bytea NOT NULL,
                    content_hash_full character varying(64) NOT NULL,
                    content_hash_masked character varying(64) NOT NULL,
                    status character varying(30) NOT NULL,
                    error_code character varying(100),
                    fallback_deadline timestamp with time zone,
                    plan_advanced_at timestamp with time zone,
                    status_changed_at timestamp with time zone,
                    fallback_requested_at timestamp with time zone,
                    sent_at timestamp with time zone,
                    delivered_at timestamp with time zone,
                    CONSTRAINT "PK_notification_attempt" PRIMARY KEY (id, created_at)
                ) PARTITION BY RANGE (created_at);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE notifications.policy_evaluation (
                    id uuid NOT NULL,
                    evaluated_at timestamp with time zone NOT NULL,
                    notification_id uuid NOT NULL,
                    rule character varying(50) NOT NULL,
                    result character varying(20) NOT NULL,
                    reason character varying(100),
                    evidence jsonb NOT NULL,
                    CONSTRAINT "PK_policy_evaluation" PRIMARY KEY (id, evaluated_at)
                ) PARTITION BY RANGE (evaluated_at);
                """);

            migrationBuilder.CreateTable(
                name: "producer_registry",
                schema: "notifications",
                columns: table => new
                {
                    principal = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    @class = table.Column<string>(name: "class", type: "character varying(20)", maxLength: 20, nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_producer_registry", x => new { x.principal, x.application, x.@class });
                });

            migrationBuilder.CreateTable(
                name: "provider_event_dedupe",
                schema: "notifications",
                columns: table => new
                {
                    provider = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    provider_event_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_provider_event_dedupe", x => new { x.provider, x.provider_event_id });
                });

            migrationBuilder.CreateIndex(
                name: "ix_delivery_event_attempt",
                schema: "notifications",
                table: "delivery_event",
                column: "attempt_id",
                filter: "attempt_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_delivery_event_notification",
                schema: "notifications",
                table: "delivery_event",
                column: "notification_id",
                filter: "notification_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_delivery_event_suppression_pending",
                schema: "notifications",
                table: "delivery_event",
                column: "received_at",
                filter: "suppression_signal <> 'none' AND applied_at IS NOT NULL AND suppression_reported_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_idempotency_key_created_at",
                schema: "notifications",
                table: "idempotency_key",
                column: "created_at");

            migrationBuilder.CreateIndex(
                name: "ix_kill_switch_hold_unreleased",
                schema: "notifications",
                table: "kill_switch_hold",
                columns: new[] { "expires_at", "id" },
                filter: "released_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ux_kill_switch_hold_work",
                schema: "notifications",
                table: "kill_switch_hold",
                columns: new[] { "work_kind", "work_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_notification_correlation",
                schema: "notifications",
                table: "notification",
                column: "correlation_id");

            migrationBuilder.CreateIndex(
                name: "ix_notification_recipient",
                schema: "notifications",
                table: "notification",
                columns: new[] { "recipient_id", "created_at" },
                descending: new[] { false, true });

            migrationBuilder.CreateIndex(
                name: "ix_notification_release_due",
                schema: "notifications",
                table: "notification",
                column: "release_at",
                filter: "status = 'deferred'");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_fallback_due",
                schema: "notifications",
                table: "notification_attempt",
                columns: new[] { "status", "fallback_deadline" },
                filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_fallback_inflight",
                schema: "notifications",
                table: "notification_attempt",
                column: "fallback_requested_at",
                filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_notification",
                schema: "notifications",
                table: "notification_attempt",
                column: "notification_id");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_provider_message",
                schema: "notifications",
                table: "notification_attempt",
                column: "provider_message_id",
                filter: "provider_message_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_unknown_due",
                schema: "notifications",
                table: "notification_attempt",
                column: "status_changed_at",
                filter: "status = 'unknown' AND fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_policy_evaluation_notification",
                schema: "notifications",
                table: "policy_evaluation",
                column: "notification_id");

            migrationBuilder.CreateIndex(
                name: "ix_provider_event_dedupe_processed",
                schema: "notifications",
                table: "provider_event_dedupe",
                column: "processed_at");

            // Without it the rear-guard job walks every partition of
            // notification_attempt and sorts the result outside the index, and
            // it misses nothing only by paying for everything.
            migrationBuilder.Sql(ReconciliationDueIndexSql);

            // The current month plus two, with the same names and the same UTC
            // boundaries the partition-manager job uses when it keeps
            // provisioning months ahead. The list is spelled out here instead
            // of read from the job: a migration is a frozen record of what it
            // created, and a list that moves with the code would rewrite
            // history the next time a table joins or leaves the job.
            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    partitioned_table text;
                    month_cursor date;
                    month_last date;
                    partition_name text;
                BEGIN
                    FOREACH partitioned_table IN ARRAY ARRAY[
                        'notification',
                        'notification_attempt',
                        'policy_evaluation',
                        'delivery_event',
                        'delivery_payload'] LOOP
                        month_cursor := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                        month_last := (month_cursor + interval '2 months')::date;
                        WHILE month_cursor <= month_last LOOP
                            partition_name := partitioned_table || '_' || to_char(month_cursor, 'YYYY_MM');
                            EXECUTE format(
                                'CREATE TABLE IF NOT EXISTS notifications.%I '
                                || 'PARTITION OF notifications.%I '
                                || 'FOR VALUES FROM (%L) TO (%L)',
                                partition_name,
                                partitioned_table,
                                month_cursor::timestamp AT TIME ZONE 'UTC',
                                (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                            month_cursor := (month_cursor + interval '1 month')::date;
                        END LOOP;
                    END LOOP;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "delivery_event",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "delivery_payload",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "idempotency_key",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "kill_switch",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "kill_switch_hold",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "notification",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "notification_attempt",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "policy_evaluation",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "producer_registry",
                schema: "notifications");

            migrationBuilder.DropTable(
                name: "provider_event_dedupe",
                schema: "notifications");
        }
    }
}
