// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Creates the ingestion state of the Notifications context: the
    /// notification table born as a parent partitioned by month on created_at
    /// (a unique index on a partitioned table must include the partition
    /// column, so the primary key is composite), with the initial monthly
    /// partitions provisioned here covering the current month plus two, using
    /// the same names and UTC boundaries as the partition-manager job that
    /// keeps provisioning future months; and the idempotency_key table, kept
    /// outside the partitioning exactly so its unique key over
    /// (application, idempotency_key) can exist.
    /// </summary>
    public partial class CreateNotificationIngestion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "notifications");

            migrationBuilder.CreateTable(
                name: "idempotency_key",
                schema: "notifications",
                columns: table => new
                {
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    idempotency_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    payload_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    notification_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_idempotency_key", x => new { x.application, x.idempotency_key });
                });

            migrationBuilder.CreateIndex(
                name: "ix_idempotency_key_created_at",
                schema: "notifications",
                table: "idempotency_key",
                column: "created_at");

            migrationBuilder.Sql("""
                CREATE TABLE notifications.notification (
                    id uuid NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    application character varying(100) NOT NULL,
                    idempotency_key character varying(200) NOT NULL,
                    recipient_id character varying(100) NOT NULL,
                    class character varying(20) NOT NULL,
                    template_key character varying(200) NOT NULL,
                    template_version integer NOT NULL,
                    policy_version integer,
                    variables_masked jsonb NOT NULL,
                    variables_enc bytea,
                    correlation_id character varying(200),
                    requested_by character varying(200) NOT NULL,
                    status character varying(30) NOT NULL,
                    release_at timestamp with time zone,
                    expires_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_notification" PRIMARY KEY (id, created_at)
                ) PARTITION BY RANGE (created_at);

                CREATE INDEX ix_notification_recipient
                    ON notifications.notification (recipient_id, created_at DESC);

                CREATE INDEX ix_notification_correlation
                    ON notifications.notification (correlation_id);
                """);

            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    month_cursor date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                    month_last date;
                    partition_name text;
                BEGIN
                    month_last := (month_cursor + interval '2 months')::date;
                    WHILE month_cursor <= month_last LOOP
                        partition_name := 'notification_' || to_char(month_cursor, 'YYYY_MM');
                        EXECUTE format(
                            'CREATE TABLE IF NOT EXISTS notifications.%I '
                            || 'PARTITION OF notifications.notification '
                            || 'FOR VALUES FROM (%L) TO (%L)',
                            partition_name,
                            month_cursor::timestamp AT TIME ZONE 'UTC',
                            (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                        month_cursor := (month_cursor + interval '1 month')::date;
                    END LOOP;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "idempotency_key",
                schema: "notifications");

            migrationBuilder.Sql("DROP TABLE notifications.notification");
        }
    }
}
