// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations;

/// <summary>
/// Adds the two materialized signals the fallback path needs: the instant a
/// plan step was advanced, which is what makes the advance happen once no
/// matter how many triggers ask for it, and whether the notification belongs
/// to an authentication flow, which is what lets a trigger name its drain band
/// without reaching the published catalog on the hot path.
/// <para>
/// The partial index over the overdue attempts is rebuilt around the new
/// column: an attempt whose step already advanced can never produce another
/// trigger, so it leaves the index instead of accumulating in it.
/// </para>
/// <para>
/// A nullable column and a column with a constant default are catalog-only
/// operations on PostgreSQL 11 and above, so neither rewrites its table. The
/// lock timeout still applies, because the index rebuild takes a lock that
/// blocks writes, and a lock that waits behind a long transaction does not
/// merely wait, it queues everything arriving after it. Rows written before
/// this migration read as outside an authentication flow, which costs them the
/// top drain band of a fallback and nothing else: no notification in flight
/// depends on this column for correctness.
/// </para>
/// </summary>
public partial class AddAttemptPlanAdvance : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_fallback",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.AddColumn<DateTimeOffset>(
            name: "plan_advanced_at",
            schema: "notifications",
            table: "notification_attempt",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<bool>(
            name: "auth_flow",
            schema: "notifications",
            table: "notification",
            type: "boolean",
            nullable: false,
            defaultValue: false);

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt",
            columns: ["status", "fallback_deadline"],
            filter: "fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.DropIndex(
            name: "ix_notification_attempt_fallback_due",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropColumn(
            name: "plan_advanced_at",
            schema: "notifications",
            table: "notification_attempt");

        migrationBuilder.DropColumn(
            name: "auth_flow",
            schema: "notifications",
            table: "notification");

        migrationBuilder.CreateIndex(
            name: "ix_notification_attempt_fallback",
            schema: "notifications",
            table: "notification_attempt",
            columns: ["status", "fallback_deadline"],
            filter: "fallback_deadline IS NOT NULL");
    }
}
