// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260825223842_StoreCallbackPayloadOnce")]
    partial class StoreCallbackPayloadOnce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.IdempotencyRegistration", b =>
                {
                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.HasKey("Application", "IdempotencyKey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_key_created_at");

                    b.ToTable("idempotency_key", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.KillSwitchHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("work_id");

                    b.Property<string>("WorkKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_kind");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "Id")
                        .HasDatabaseName("ix_kill_switch_hold_unreleased")
                        .HasFilter("released_at IS NULL");

                    b.HasIndex("WorkKind", "WorkId")
                        .IsUnique()
                        .HasDatabaseName("ux_kill_switch_hold_work");

                    b.ToTable("kill_switch_hold", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_kill_switch_hold_scope", "scope IN ('producer', 'application', 'channel')");

                            t.HasCheckConstraint("ck_kill_switch_hold_version", "version > 0");

                            t.HasCheckConstraint("ck_kill_switch_hold_work_kind", "work_kind IN ('core', 'fallback', 'dispatch')");
                        });
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.KillSwitchState", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("SecondActor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("second_actor");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Scope", "Key");

                    b.ToTable("kill_switch", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_kill_switch_scope", "scope IN ('producer', 'application', 'channel')");

                            t.HasCheckConstraint("ck_kill_switch_state", "state IN ('active', 'inactive')");

                            t.HasCheckConstraint("ck_kill_switch_version", "version > 0");
                        });
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("AdmittedPlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("admitted_plan");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<bool>("AuthFlow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auth_flow");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset?>("ReleaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<byte[]>("VariablesEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("variables_enc");

                    b.Property<string>("VariablesMaskedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_masked");

                    b.HasKey("Id", "CreatedAt");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_notification_correlation");

                    b.HasIndex("ReleaseAt")
                        .HasDatabaseName("ix_notification_release_due")
                        .HasFilter("status = 'deferred'");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notification_recipient");

                    b.ToTable("notification", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid?>("ContactPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_point_id");

                    b.Property<string>("ContentHashFull")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash_full");

                    b.Property<string>("ContentHashMasked")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash_masked");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("DeviceTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_token_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("FallbackDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fallback_deadline");

                    b.Property<DateTimeOffset?>("FallbackRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fallback_requested_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset?>("PlanAdvancedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_advanced_at");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<byte[]>("RenderedContentEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("rendered_content_enc");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.HasKey("Id", "CreatedAt");

                    b.HasIndex("FallbackRequestedAt")
                        .HasDatabaseName("ix_notification_attempt_fallback_inflight")
                        .HasFilter("fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NOT NULL");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_notification_attempt_notification");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("ix_notification_attempt_provider_message")
                        .HasFilter("provider_message_id IS NOT NULL");

                    b.HasIndex("StatusChangedAt")
                        .HasDatabaseName("ix_notification_attempt_unknown_due")
                        .HasFilter("status = 'unknown' AND fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NULL");

                    b.HasIndex("Status", "FallbackDeadline")
                        .HasDatabaseName("ix_notification_attempt_fallback_due")
                        .HasFilter("fallback_deadline IS NOT NULL AND plan_advanced_at IS NULL AND fallback_requested_at IS NULL");

                    b.ToTable("notification_attempt", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.PolicyEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule");

                    b.HasKey("Id", "EvaluatedAt");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_policy_evaluation_notification");

                    b.ToTable("policy_evaluation", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Domain.ProducerRegistration", b =>
                {
                    b.Property<string>("Principal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("principal");

                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<string>("Class")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Principal", "Application", "Class");

                    b.ToTable("producer_registry", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Features.DeliveryTracking.DeliveryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("payload_id");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_event_id");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SuppressionReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppression_reported_at");

                    b.Property<string>("SuppressionSignal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("suppression_signal");

                    b.HasKey("Id", "ReceivedAt");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_delivery_event_attempt")
                        .HasFilter("attempt_id IS NOT NULL");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_delivery_event_notification")
                        .HasFilter("notification_id IS NOT NULL");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_delivery_event_suppression_pending")
                        .HasFilter("suppression_signal <> 'none' AND applied_at IS NOT NULL AND suppression_reported_at IS NULL");

                    b.ToTable("delivery_event", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Features.DeliveryTracking.DeliveryPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<byte[]>("PayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_enc");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("Id", "ReceivedAt");

                    b.ToTable("delivery_payload", "notifications");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.Notifications.Features.DeliveryTracking.ProviderEventDedupe", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Provider", "ProviderEventId");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_provider_event_dedupe_processed");

                    b.ToTable("provider_event_dedupe", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
