// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Stores the suppression signal alongside the delivery evidence it came
    /// with. Until now the column did not exist and the consumer rebuilt the
    /// canonical event with a neutral signal, so no refusal of a destination
    /// ever reached the contact ledger: the evidence was complete about the
    /// attempt and silent about the address.
    /// <para>
    /// The column takes the classification the provider adapters already made,
    /// never a second reading of the failure code here. Which codes are
    /// definitive is provider knowledge on an operator-configured list, and a
    /// classifier on this side would drift from it the first time a provider
    /// revised a code.
    /// </para>
    /// <para>
    /// Rows written before this migration read <c>none</c>, which is the value
    /// the missing column already meant, so nothing is invented. Adding a column
    /// with a constant default is a catalog-only operation on PostgreSQL 11 and
    /// above and rewrites neither the parent nor its partitions; the lock it
    /// takes on the parent is still exclusive and still blocks the ingestion
    /// behind it, which is why the lock timeout applies here as it does to every
    /// migration of this class.
    /// </para>
    /// </summary>
    public partial class AddDeliveryEventSuppressionSignal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

            migrationBuilder.AddColumn<string>(
                name: "suppression_signal",
                schema: "notifications",
                table: "delivery_event",
                type: "character varying(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "none");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

            migrationBuilder.DropColumn(
                name: "suppression_signal",
                schema: "notifications",
                table: "delivery_event");
        }
    }
}
