// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Creates the pipeline state of the Notifications context: the
    /// notification_attempt and policy_evaluation tables born as parents
    /// partitioned by month (a unique index on a partitioned table must
    /// include the partition column, so both primary keys are composite),
    /// with the initial monthly partitions provisioned here covering the
    /// current month plus two, using the same names and UTC boundaries as the
    /// partition-manager job; plus the partial release index the deferred
    /// release scan needs on the notification table.
    /// </summary>
    public partial class CreateCorePipelineState : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE notifications.notification_attempt (
                    id uuid NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    notification_id uuid NOT NULL,
                    sequence integer NOT NULL,
                    channel character varying(20) NOT NULL,
                    provider_key character varying(50),
                    contact_point_id uuid,
                    provider_message_id character varying(200),
                    rendered_content_enc bytea NOT NULL,
                    content_hash_full character varying(64) NOT NULL,
                    content_hash_masked character varying(64) NOT NULL,
                    status character varying(30) NOT NULL,
                    error_code character varying(100),
                    fallback_deadline timestamp with time zone,
                    sent_at timestamp with time zone,
                    delivered_at timestamp with time zone,
                    CONSTRAINT "PK_notification_attempt" PRIMARY KEY (id, created_at)
                ) PARTITION BY RANGE (created_at);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE notifications.policy_evaluation (
                    id uuid NOT NULL,
                    evaluated_at timestamp with time zone NOT NULL,
                    notification_id uuid NOT NULL,
                    rule character varying(50) NOT NULL,
                    result character varying(20) NOT NULL,
                    reason character varying(100),
                    evidence jsonb NOT NULL,
                    CONSTRAINT "PK_policy_evaluation" PRIMARY KEY (id, evaluated_at)
                ) PARTITION BY RANGE (evaluated_at);
                """);

            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    month_start date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                    month_cursor date;
                    month_last date;
                    parent text;
                    partition_name text;
                BEGIN
                    month_last := (month_start + interval '2 months')::date;
                    FOREACH parent IN ARRAY ARRAY['notification_attempt', 'policy_evaluation'] LOOP
                        month_cursor := month_start;
                        WHILE month_cursor <= month_last LOOP
                            partition_name := parent || '_' || to_char(month_cursor, 'YYYY_MM');
                            EXECUTE format(
                                'CREATE TABLE IF NOT EXISTS notifications.%I '
                                || 'PARTITION OF notifications.%I '
                                || 'FOR VALUES FROM (%L) TO (%L)',
                                partition_name,
                                parent,
                                month_cursor::timestamp AT TIME ZONE 'UTC',
                                (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                            month_cursor := (month_cursor + interval '1 month')::date;
                        END LOOP;
                    END LOOP;
                END $$;
                """);

            migrationBuilder.CreateIndex(
                name: "ix_notification_release",
                schema: "notifications",
                table: "notification",
                column: "release_at",
                filter: "release_at IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_fallback",
                schema: "notifications",
                table: "notification_attempt",
                columns: new[] { "status", "fallback_deadline" },
                filter: "fallback_deadline IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_notification_attempt_notification",
                schema: "notifications",
                table: "notification_attempt",
                column: "notification_id");

            migrationBuilder.CreateIndex(
                name: "ix_policy_evaluation_notification",
                schema: "notifications",
                table: "policy_evaluation",
                column: "notification_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE notifications.notification_attempt");

            migrationBuilder.Sql("DROP TABLE notifications.policy_evaluation");

            migrationBuilder.DropIndex(
                name: "ix_notification_release",
                schema: "notifications",
                table: "notification");
        }
    }
}
