// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Makes the suppression report durable, and makes the rear-guard
    /// reconciliation reach the rows it exists for.
    /// <para>
    /// <c>suppression_reported_at</c> is the retry the queue cannot provide. A
    /// refused destination is reported to the contact ledger after the
    /// transition commits, because the ledger belongs to another context and
    /// reporting earlier would stop addressing a person on the strength of a
    /// callback that ended up applying nothing. Outside the transaction, a
    /// transient failure of that module used to lose the signal for good: the
    /// event is already applied and already deduplicated, so no redelivery ever
    /// revisits it. The stamp turns the debt into a fact in the database, and
    /// the partial index makes proving there is no debt cost an index probe on
    /// the scheduler interval rather than a walk of every partition.
    /// </para>
    /// <para>
    /// The second index is the one the reconciliation candidate statement never
    /// had. Its predicate matched none of the four partial indexes on the
    /// table, so a job whose whole point is to be cheap read every partition of
    /// <c>notification_attempt</c> and sorted the result externally. The index
    /// is on the same coalesce the statement filters and orders by, and the
    /// substitution is not cosmetic: it is what reaches the attempts parked
    /// before <c>status_changed_at</c> existed, which are precisely the rows
    /// that job was created to resolve.
    /// </para>
    /// <para>
    /// Both are catalog-only operations on the parent: adding a nullable column
    /// with no default rewrites neither the parent nor its partitions, and an
    /// index created on a partitioned parent is built per partition. The lock
    /// on the parent is still exclusive and still blocks the ingestion behind
    /// it, which is why the lock timeout applies here as it does to every
    /// migration of this class.
    /// </para>
    /// </summary>
    public partial class AddDeliverySuppressionReportState : Migration
    {
        /// <summary>
        /// The reconciliation index, written by hand because the expression it
        /// is built on is not something the model can carry. It is the same
        /// coalesce the candidate statement spells, so the two are read
        /// together or not at all.
        /// </summary>
        internal const string ReconciliationDueIndexSql = """
            CREATE INDEX ix_notification_attempt_reconciliation_due
                ON notifications.notification_attempt (COALESCE(status_changed_at, created_at))
             WHERE status IN ('sent', 'unknown')
               AND provider_key IS NOT NULL
            """;

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "suppression_reported_at",
                schema: "notifications",
                table: "delivery_event",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_delivery_event_suppression_pending",
                schema: "notifications",
                table: "delivery_event",
                column: "received_at",
                filter: "suppression_signal <> 'none' AND applied_at IS NOT NULL AND suppression_reported_at IS NULL");

            migrationBuilder.Sql(ReconciliationDueIndexSql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX notifications.ix_notification_attempt_reconciliation_due");

            migrationBuilder.DropIndex(
                name: "ix_delivery_event_suppression_pending",
                schema: "notifications",
                table: "delivery_event");

            migrationBuilder.DropColumn(
                name: "suppression_reported_at",
                schema: "notifications",
                table: "delivery_event");
        }
    }
}
