// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations;

public partial class AddKillSwitch : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "kill_switch",
            schema: "notifications",
            columns: table => new
            {
                scope = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                state = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                version = table.Column<long>(type: "bigint", nullable: false),
                actor = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                second_actor = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_kill_switch", row => new { row.scope, row.key });
                table.CheckConstraint(
                    "ck_kill_switch_scope",
                    "scope IN ('producer', 'application', 'channel')");
                table.CheckConstraint(
                    "ck_kill_switch_state",
                    "state IN ('active', 'inactive')");
                table.CheckConstraint("ck_kill_switch_version", "version > 0");
            });

        migrationBuilder.CreateTable(
            name: "kill_switch_hold",
            schema: "notifications",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                work_kind = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                work_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                scope = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                destination = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                payload = table.Column<string>(type: "jsonb", nullable: false),
                expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                released_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                version = table.Column<long>(type: "bigint", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_kill_switch_hold", row => row.id);
                table.CheckConstraint(
                    "ck_kill_switch_hold_scope",
                    "scope IN ('producer', 'application', 'channel')");
                table.CheckConstraint("ck_kill_switch_hold_version", "version > 0");
                table.CheckConstraint(
                    "ck_kill_switch_hold_work_kind",
                    "work_kind IN ('core', 'fallback', 'dispatch')");
            });

        migrationBuilder.CreateIndex(
            name: "ix_kill_switch_hold_unreleased",
            schema: "notifications",
            table: "kill_switch_hold",
            columns: ["expires_at", "id"],
            filter: "released_at IS NULL");

        migrationBuilder.CreateIndex(
            name: "ux_kill_switch_hold_work",
            schema: "notifications",
            table: "kill_switch_hold",
            columns: ["work_kind", "work_id"],
            unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "kill_switch", schema: "notifications");
        migrationBuilder.DropTable(name: "kill_switch_hold", schema: "notifications");
    }
}
