// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.Notifications.Infrastructure.Persistence.Migrations;

/// <summary>
/// Moves the verified callback bytes out of every delivery_event row and into
/// one delivery_payload row per callback, referenced by payload_id. Storing the
/// batch inside each of its own events made the write quadratic in the batch
/// size, which is a variable the provider chooses.
/// <para>
/// The new table is born partitioned by month on received_at, on the same
/// boundaries as delivery_event, because the reception instant is stamped once
/// per callback and every event of that callback carries it. The alignment is
/// what lets a later retention retire the body on a clock of its own.
/// </para>
/// <para>
/// There is no backfill. payload_id is added NOT NULL without a default, so a
/// table that already holds evidence refuses the migration instead of inventing
/// a callback for rows whose bytes it cannot attribute.
/// </para>
/// </summary>
public partial class StoreCallbackPayloadOnce : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Standing rule for any migration of this class: a lock that waits
        // behind a long transaction does not merely wait, it queues everything
        // arriving after it. Failing fast and rescheduling costs less than
        // stalling ingestion for an unbounded time.
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.Sql("""
            CREATE TABLE notifications.delivery_payload (
                id uuid NOT NULL,
                received_at timestamp with time zone NOT NULL,
                provider_key character varying(50) NOT NULL,
                source character varying(20) NOT NULL,
                payload_enc bytea NOT NULL,
                CONSTRAINT "PK_delivery_payload" PRIMARY KEY (id, received_at)
            ) PARTITION BY RANGE (received_at);
            """);

        migrationBuilder.Sql("""
            DO $$
            DECLARE
                month_start date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                month_cursor date;
                month_last date;
                partition_name text;
            BEGIN
                month_last := (month_start + interval '2 months')::date;
                month_cursor := month_start;
                WHILE month_cursor <= month_last LOOP
                    partition_name := 'delivery_payload_' || to_char(month_cursor, 'YYYY_MM');
                    EXECUTE format(
                        'CREATE TABLE IF NOT EXISTS notifications.%I '
                        || 'PARTITION OF notifications.delivery_payload '
                        || 'FOR VALUES FROM (%L) TO (%L)',
                        partition_name,
                        month_cursor::timestamp AT TIME ZONE 'UTC',
                        (month_cursor + interval '1 month')::timestamp AT TIME ZONE 'UTC');
                    month_cursor := (month_cursor + interval '1 month')::date;
                END LOOP;
            END $$;
            """);

        migrationBuilder.Sql("""
            ALTER TABLE notifications.delivery_event
                ADD COLUMN payload_id uuid NOT NULL,
                DROP COLUMN payload_enc;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

        migrationBuilder.Sql("""
            ALTER TABLE notifications.delivery_event
                ADD COLUMN payload_enc bytea NOT NULL,
                DROP COLUMN payload_id;
            """);

        migrationBuilder.Sql("DROP TABLE notifications.delivery_payload");
    }
}
