<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NotificationHub.IntegrationTests</RootNamespace>
    <AssemblyName>NotificationHub.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\src\Platform.Api\Platform.Api.csproj" />
    <ProjectReference Include="..\..\src\Platform.Worker\Platform.Worker.csproj" />
    <ProjectReference Include="..\..\tools\Platform.GoLiveChecks\Platform.GoLiveChecks.csproj" />
  </ItemGroup>

  <ItemGroup Label="Implicit Usings">
    <Using Include="Microsoft.AspNetCore.Mvc.Testing" />
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup Label="Test Framework">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Testcontainers.LocalStack" />
    <PackageReference Include="Testcontainers.Kafka" />
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>

</Project>
