// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "attachmentmanagement");

            migrationBuilder.CreateTable(
                name: "attachment",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    reference = table.Column<string>(type: "character varying(36)", maxLength: 36, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    file_name = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    content_type = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    size_bytes = table.Column<long>(type: "bigint", nullable: false),
                    content_id = table.Column<Guid>(type: "uuid", nullable: false),
                    state = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    received_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    validation_detail = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: true),
                    inconclusive_until = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    ended_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    reconciliation_liability = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_attachment", x => x.id);
                    table.CheckConstraint("ck_attachment_size_positive", "size_bytes > 0");
                });

            migrationBuilder.CreateTable(
                name: "producer_application_grant",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    issuer = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    claim_kind = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    principal_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    application = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_producer_application_grant", x => new { x.issuer, x.claim_kind, x.principal_id, x.application });
                });

            migrationBuilder.CreateTable(
                name: "attachment_dependency",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    attachment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reason = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    holder = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    acquired_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    released_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    version = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_attachment_dependency", x => x.id);
                    table.ForeignKey(
                        name: "FK_attachment_dependency_attachment_attachment_id",
                        column: x => x.attachment_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "attachment_object_generation",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    attachment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    object_key = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    version = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: false),
                    digest_algorithm = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    digest = table.Column<byte[]>(type: "bytea", nullable: false),
                    length_bytes = table.Column<long>(type: "bigint", nullable: false),
                    detected_content_type = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    captured_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_attachment_object_generation", x => x.id);
                    table.CheckConstraint("ck_attachment_object_generation_length_not_negative", "length_bytes >= 0");
                    table.CheckConstraint("ck_attachment_object_generation_version_not_blank", "btrim(version) <> ''");
                    table.ForeignKey(
                        name: "FK_attachment_object_generation_attachment_attachment_id",
                        column: x => x.attachment_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "attachment_release",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    attachment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    generation_id = table.Column<Guid>(type: "uuid", nullable: false),
                    released_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_attachment_release", x => x.id);
                    table.CheckConstraint("ck_attachment_release_expiry_after_release", "expires_at > released_at");
                    table.ForeignKey(
                        name: "FK_attachment_release_attachment_attachment_id",
                        column: x => x.attachment_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_attachment_release_attachment_object_generation_generation_~",
                        column: x => x.generation_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment_object_generation",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "attachment_revocation",
                schema: "attachmentmanagement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    attachment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    release_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reason = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    revoked_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_attachment_revocation", x => x.id);
                    table.ForeignKey(
                        name: "FK_attachment_revocation_attachment_attachment_id",
                        column: x => x.attachment_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_attachment_revocation_attachment_release_release_id",
                        column: x => x.release_id,
                        principalSchema: "attachmentmanagement",
                        principalTable: "attachment_release",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_attachment_abandonment",
                schema: "attachmentmanagement",
                table: "attachment",
                column: "created_at",
                filter: "state IN ('awaiting-upload', 'received', 'rejected', 'revoked')");

            migrationBuilder.CreateIndex(
                name: "ix_attachment_reconciliation_liability",
                schema: "attachmentmanagement",
                table: "attachment",
                column: "created_at",
                filter: "reconciliation_liability IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ux_attachment_content_id",
                schema: "attachmentmanagement",
                table: "attachment",
                column: "content_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ux_attachment_reference",
                schema: "attachmentmanagement",
                table: "attachment",
                column: "reference",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_attachment_dependency_live",
                schema: "attachmentmanagement",
                table: "attachment_dependency",
                column: "attachment_id",
                filter: "released_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ux_attachment_dependency_holder",
                schema: "attachmentmanagement",
                table: "attachment_dependency",
                columns: new[] { "attachment_id", "holder" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_attachment_object_generation_attachment",
                schema: "attachmentmanagement",
                table: "attachment_object_generation",
                column: "attachment_id");

            migrationBuilder.CreateIndex(
                name: "ux_attachment_object_generation_version",
                schema: "attachmentmanagement",
                table: "attachment_object_generation",
                columns: new[] { "store", "object_key", "version" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_attachment_release_attachment",
                schema: "attachmentmanagement",
                table: "attachment_release",
                column: "attachment_id");

            migrationBuilder.CreateIndex(
                name: "IX_attachment_release_generation_id",
                schema: "attachmentmanagement",
                table: "attachment_release",
                column: "generation_id");

            migrationBuilder.CreateIndex(
                name: "ix_attachment_revocation_attachment",
                schema: "attachmentmanagement",
                table: "attachment_revocation",
                column: "attachment_id");

            migrationBuilder.CreateIndex(
                name: "ux_attachment_revocation_release",
                schema: "attachmentmanagement",
                table: "attachment_revocation",
                column: "release_id",
                unique: true);

            // The generation line is the only durable proof of which bytes an
            // attachment held: version, digest and length, written once when
            // the content was captured. The mapping already refuses to revise
            // a tracked instance, but a set-based update and raw SQL go around
            // the change tracker, so the guard that actually closes the record
            // has to live here, in the same dialect as the audit trail and the
            // consent ledger.
            //
            // The rejection is unconditional on purpose. A per-column
            // condition would have to name every frozen column, and the same
            // shape applied to a table whose rows do change would refuse an
            // unrelated column too. Here nothing on the row is ever meant to
            // move, so the whole statement is what gets refused.
            migrationBuilder.Sql("""
                CREATE FUNCTION attachmentmanagement.reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Table %.% is append-only: % is not allowed.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
                END $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_attachment_object_generation_append_only
                    BEFORE UPDATE OR DELETE ON attachmentmanagement.attachment_object_generation
                    FOR EACH ROW EXECUTE FUNCTION attachmentmanagement.reject_append_only_mutation();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "attachment_dependency",
                schema: "attachmentmanagement");

            migrationBuilder.DropTable(
                name: "attachment_revocation",
                schema: "attachmentmanagement");

            migrationBuilder.DropTable(
                name: "producer_application_grant",
                schema: "attachmentmanagement");

            migrationBuilder.DropTable(
                name: "attachment_release",
                schema: "attachmentmanagement");

            migrationBuilder.DropTable(
                name: "attachment_object_generation",
                schema: "attachmentmanagement");

            migrationBuilder.DropTable(
                name: "attachment",
                schema: "attachmentmanagement");

            migrationBuilder.Sql(
                "DROP FUNCTION IF EXISTS attachmentmanagement.reject_append_only_mutation()");
        }
    }
}
