// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AttachmentManagementDbContext))]
    partial class AttachmentManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attachmentmanagement")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset?>("InconclusiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inconclusive_until");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ReconciliationLiability")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reconciliation_liability");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("reference");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("ValidationDetail")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("validation_detail");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_content_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_attachment_reconciliation_liability")
                        .HasFilter("reconciliation_liability IS NOT NULL");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_reference");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_attachment_abandonment")
                        .HasDatabaseName("ix_attachment_abandonment")
                        .HasFilter("state IN ('awaiting-upload', 'received', 'rejected', 'revoked')");

                    b.ToTable("attachment", "attachmentmanagement", t =>
                        {
                            t.HasCheckConstraint("ck_attachment_size_positive", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Domain.ProducerApplicationGrant", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<string>("ClaimKind")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claim_kind");

                    b.Property<string>("PrincipalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("principal_id");

                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.HasKey("Issuer", "ClaimKind", "PrincipalId", "Application");

                    b.ToTable("producer_application_grant", "attachmentmanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<string>("Holder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("holder");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_attachment_dependency_live")
                        .HasFilter("released_at IS NULL");

                    b.HasIndex("AttachmentId", "Holder")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_dependency_holder");

                    b.ToTable("attachment_dependency", "attachmentmanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentObjectGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("digest_algorithm");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("detected_content_type");

                    b.Property<byte[]>("Digest")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("digest");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("length_bytes");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("store");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_attachment_object_generation_attachment");

                    b.HasIndex("Store", "Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_object_generation_version");

                    b.ToTable("attachment_object_generation", "attachmentmanagement", t =>
                        {
                            t.HasCheckConstraint("ck_attachment_object_generation_length_not_negative", "length_bytes >= 0");

                            t.HasCheckConstraint("ck_attachment_object_generation_version_not_blank", "btrim(version) <> ''");
                        });
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_attachment_release_attachment");

                    b.HasIndex("GenerationId");

                    b.ToTable("attachment_release", "attachmentmanagement", t =>
                        {
                            t.HasCheckConstraint("ck_attachment_release_expiry_after_release", "expires_at > released_at");
                        });
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentRevocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_attachment_revocation_attachment");

                    b.HasIndex("ReleaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_attachment_revocation_release");

                    b.ToTable("attachment_revocation", "attachmentmanagement");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentDependency", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Domain.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentObjectGeneration", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Domain.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentRelease", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Domain.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentObjectGeneration", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentRevocation", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Domain.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotificationHub.Api.Modules.AttachmentManagement.Infrastructure.Persistence.AttachmentRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
