// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.ContactConsent.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Creates the suppression ledger of the ContactConsent context: the
    /// append-only record of every refusal a provider reported, and the
    /// suppressions those refusals accumulated into.
    /// <para>
    /// The unique key over <c>source_event_id</c> is the whole idempotency of
    /// the delivery-feedback path: the reporting side hands over the identity
    /// of the evidence row it read, and a redelivery of the internal message
    /// collides here instead of counting a second refusal that never happened.
    /// </para>
    /// <para>
    /// The partial unique index over the suppressions in force is what keeps a
    /// reversal honest. Without it two concurrent reports would leave two rows
    /// standing, an operator would take back one of them, and the contact point
    /// would stay unaddressable with nothing on screen explaining why. Removed
    /// rows stay out of the index and in the table, because the reason a message
    /// was never sent has to survive the reversal.
    /// </para>
    /// <para>
    /// Both tables are born empty, so nothing is rewritten. What takes a lock
    /// that blocks writes is the foreign key to <c>contact_point</c>, and a lock
    /// that waits behind a long transaction does not merely wait: it queues
    /// everything arriving after it. Hence the lock timeout, this repository's
    /// standard for a migration of this class.
    /// </para>
    /// </summary>
    public partial class AddSuppressionLedger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

            migrationBuilder.CreateTable(
                name: "suppression",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    contact_point_id = table.Column<Guid>(type: "uuid", nullable: false),
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    reason = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    source = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    actor_type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    actor_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    until = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    removed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    removed_by = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_suppression", x => x.id);
                    table.ForeignKey(
                        name: "FK_suppression_contact_point_contact_point_id",
                        column: x => x.contact_point_id,
                        principalSchema: "contactconsent",
                        principalTable: "contact_point",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "suppression_signal",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    contact_point_id = table.Column<Guid>(type: "uuid", nullable: false),
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    reason = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    source_event_id = table.Column<Guid>(type: "uuid", nullable: false),
                    observed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_suppression_signal", x => x.id);
                    table.ForeignKey(
                        name: "FK_suppression_signal_contact_point_contact_point_id",
                        column: x => x.contact_point_id,
                        principalSchema: "contactconsent",
                        principalTable: "contact_point",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ux_suppression_contact_point_active",
                schema: "contactconsent",
                table: "suppression",
                column: "contact_point_id",
                unique: true,
                filter: "removed_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_suppression_signal_contact_point_observed",
                schema: "contactconsent",
                table: "suppression_signal",
                columns: new[] { "contact_point_id", "observed_at" });

            migrationBuilder.CreateIndex(
                name: "ux_suppression_signal_source_event",
                schema: "contactconsent",
                table: "suppression_signal",
                column: "source_event_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET LOCAL lock_timeout = '3s'");

            migrationBuilder.DropTable(
                name: "suppression",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "suppression_signal",
                schema: "contactconsent");
        }
    }
}
