// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationHub.Api.Modules.ContactConsent.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationHub.Api.Modules.ContactConsent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContactConsentDbContext))]
    [Migration("20260825023154_AddSuppressionLedger")]
    partial class AddSuppressionLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contactconsent")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ContactPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_point_id");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terms_version");

                    b.HasKey("Id");

                    b.HasIndex("ContactPointId", "Purpose", "RecordedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_consent_point_purpose_recorded");

                    b.ToTable("consent", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<byte[]>("ValueEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_enc");

                    b.Property<string>("ValueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value_hash");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.HasIndex("ValueHash")
                        .HasDatabaseName("ix_contact_point_value_hash");

                    b.HasIndex("RecipientId", "Channel", "ValueHash")
                        .IsUnique()
                        .HasDatabaseName("ux_contact_point_recipient_channel_value");

                    b.ToTable("contact_point", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.ContactSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContactPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_point_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("RemovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("removed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.HasKey("Id");

                    b.HasIndex("ContactPointId")
                        .IsUnique()
                        .HasDatabaseName("ux_suppression_contact_point_active")
                        .HasFilter("removed_at IS NULL");

                    b.ToTable("suppression", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "LastSeenAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_device_token_recipient_last_seen");

                    b.HasIndex("RecipientId", "Token")
                        .IsUnique()
                        .HasDatabaseName("ux_device_token_recipient_token");

                    b.ToTable("device_token", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.RecipientProfile", b =>
                {
                    b.Property<string>("RecipientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Locale")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("locale");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RecipientId");

                    b.ToTable("recipient_profile", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.SuppressionSignalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContactPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_point_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_suppression_signal_source_event");

                    b.HasIndex("ContactPointId", "ObservedAt")
                        .HasDatabaseName("ix_suppression_signal_contact_point_observed");

                    b.ToTable("suppression_signal", "contactconsent");
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.Consent", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.ContactConsent.Domain.ContactPoint", null)
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.ContactPoint", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.ContactConsent.Domain.RecipientProfile", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.ContactSuppression", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.ContactConsent.Domain.ContactPoint", null)
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.DeviceToken", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.ContactConsent.Domain.RecipientProfile", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationHub.Api.Modules.ContactConsent.Domain.SuppressionSignalRecord", b =>
                {
                    b.HasOne("NotificationHub.Api.Modules.ContactConsent.Domain.ContactPoint", null)
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
