// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NotificationHub.Api.Modules.ContactConsent.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "contactconsent");

            migrationBuilder.CreateTable(
                name: "recipient_profile",
                schema: "contactconsent",
                columns: table => new
                {
                    recipient_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    timezone = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    locale = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_recipient_profile", x => x.recipient_id);
                });

            migrationBuilder.CreateTable(
                name: "contact_point",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    recipient_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    value_enc = table.Column<byte[]>(type: "bytea", nullable: false),
                    value_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    verified = table.Column<bool>(type: "boolean", nullable: false),
                    removed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_contact_point", x => x.id);
                    table.ForeignKey(
                        name: "FK_contact_point_recipient_profile_recipient_id",
                        column: x => x.recipient_id,
                        principalSchema: "contactconsent",
                        principalTable: "recipient_profile",
                        principalColumn: "recipient_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "device_token",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    recipient_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    token = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    platform = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    app_version = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    registered_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    last_seen_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    invalidated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_device_token", x => x.id);
                    table.ForeignKey(
                        name: "FK_device_token_recipient_profile_recipient_id",
                        column: x => x.recipient_id,
                        principalSchema: "contactconsent",
                        principalTable: "recipient_profile",
                        principalColumn: "recipient_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "consent",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    contact_point_id = table.Column<Guid>(type: "uuid", nullable: false),
                    purpose = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    granted = table.Column<bool>(type: "boolean", nullable: false),
                    source = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    actor_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    terms_version = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    recorded_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_consent", x => x.id);
                    table.ForeignKey(
                        name: "FK_consent_contact_point_contact_point_id",
                        column: x => x.contact_point_id,
                        principalSchema: "contactconsent",
                        principalTable: "contact_point",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "suppression",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    contact_point_id = table.Column<Guid>(type: "uuid", nullable: false),
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    reason = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    source = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    actor_type = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    actor_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    until = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    removed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    removed_by = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_suppression", x => x.id);
                    table.ForeignKey(
                        name: "FK_suppression_contact_point_contact_point_id",
                        column: x => x.contact_point_id,
                        principalSchema: "contactconsent",
                        principalTable: "contact_point",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "suppression_signal",
                schema: "contactconsent",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    contact_point_id = table.Column<Guid>(type: "uuid", nullable: false),
                    channel = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    reason = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    source_event_id = table.Column<Guid>(type: "uuid", nullable: false),
                    observed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_suppression_signal", x => x.id);
                    table.ForeignKey(
                        name: "FK_suppression_signal_contact_point_contact_point_id",
                        column: x => x.contact_point_id,
                        principalSchema: "contactconsent",
                        principalTable: "contact_point",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_consent_point_purpose_recorded",
                schema: "contactconsent",
                table: "consent",
                columns: new[] { "contact_point_id", "purpose", "recorded_at" },
                descending: new[] { false, false, true });

            migrationBuilder.CreateIndex(
                name: "ix_contact_point_value_hash",
                schema: "contactconsent",
                table: "contact_point",
                column: "value_hash");

            migrationBuilder.CreateIndex(
                name: "ux_contact_point_recipient_channel_value",
                schema: "contactconsent",
                table: "contact_point",
                columns: new[] { "recipient_id", "channel", "value_hash" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_device_token_recipient_last_seen",
                schema: "contactconsent",
                table: "device_token",
                columns: new[] { "recipient_id", "last_seen_at" },
                descending: new[] { false, true });

            migrationBuilder.CreateIndex(
                name: "ux_device_token_recipient_token",
                schema: "contactconsent",
                table: "device_token",
                columns: new[] { "recipient_id", "token" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ux_suppression_contact_point_active",
                schema: "contactconsent",
                table: "suppression",
                column: "contact_point_id",
                unique: true,
                filter: "removed_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_suppression_signal_contact_point_observed",
                schema: "contactconsent",
                table: "suppression_signal",
                columns: new[] { "contact_point_id", "observed_at" });

            migrationBuilder.CreateIndex(
                name: "ux_suppression_signal_source_event",
                schema: "contactconsent",
                table: "suppression_signal",
                column: "source_event_id",
                unique: true);

            // The consent ledger is append-only by construction: the current
            // state of a (purpose, channel) pair is always the latest record,
            // and a row trigger rejects any UPDATE or DELETE, in the same
            // dialect as the audit trail guard. The function is owned by this
            // module's schema so the guard never depends on a sibling context.
            migrationBuilder.Sql("""
                CREATE FUNCTION contactconsent.reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Table %.% is append-only: % is not allowed.',
                        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
                END $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_consent_append_only
                    BEFORE UPDATE OR DELETE ON contactconsent.consent
                    FOR EACH ROW EXECUTE FUNCTION contactconsent.reject_append_only_mutation();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "consent",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "device_token",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "suppression",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "suppression_signal",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "contact_point",
                schema: "contactconsent");

            migrationBuilder.DropTable(
                name: "recipient_profile",
                schema: "contactconsent");

            migrationBuilder.Sql(
                "DROP FUNCTION IF EXISTS contactconsent.reject_append_only_mutation()");
        }
    }
}
